/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false cloudflare-env.d.ts` (hash: 7d9f4802a61c2df2e4283eba8057e9c7)
interface __BaseEnv_Env {
	LOCAL_LORE_DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	LOCAL_LORE_IMAGE_DAILY_LIMIT: string;
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
	TEMPLATES_AI_ORDERS: DurableObjectNamespace<import("./worker").TemplateAiOrder>;
	TEMPLATES_TRIAL_CODES: DurableObjectNamespace<import("./worker").TemplateTrialCodes>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "TemplateAiOrder" | "TemplateTrialCodes";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
