/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false cloudflare-env.d.ts` (hash: 8d7a9ffb8ed9934eeb8f17441ce5de9a)
interface __BaseEnv_Env {
	LOCAL_LORE_DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	LOCAL_LORE_IMAGE_DAILY_LIMIT: string;
	NEXT_PUBLIC_META_PIXEL_ID: string;
	TEMPLATES_AI_ENABLED: string;
	TEMPLATES_AI_MODEL: string;
	TEMPLATES_AI_REASONING_EFFORT: string;
	TEMPLATES_ICON_ENABLED: string;
	TEMPLATES_ICON_MODEL: string;
	TEMPLATES_TRIAL_ENABLED: string;
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
	HF_API_KEY_SECRET: string;
	HF_API_KEY_ID: string;
	TEMPLATES_AI_ORDERS: DurableObjectNamespace<import("./worker").TemplateAiOrder>;
	TEMPLATES_TRIAL_CODES: DurableObjectNamespace<import("./worker").TemplateTrialCodes>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "TemplateAiOrder" | "TemplateTrialCodes";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
