import "server-only";

export const browserGamePrompt = String.raw`Build a production-ready, original browser geography game using the customization brief supplied with this prompt. Use synthetic locations and placeholder branding during development. Do not reproduce any reference project's name, wording, artwork, domains, identifiers, location catalog, coordinates, source links, pricing, or private data. The result must be a complete repository with browser assets, server API, database migrations, tests, setup documentation, privacy and terms pages, deployment instructions, and a maintenance runbook.

Use a static, framework-free browser interface with semantic HTML, responsive CSS, and small ES modules. Implement the server as a framework-neutral Cloudflare Worker route module and use Cloudflare D1 for production persistence. Provide a Node 22.14+ local server with a SQLite-compatible adapter or an equally faithful local D1 workflow. Keep pure scoring, map projection, region configuration, catalog validation, selection, and entitlement logic isolated from HTTP and storage so they can be unit tested without network calls.

Create three configurable three-round modes: a same-for-everyone daily challenge, repeatable intersection or neighborhood practice, and landmark practice. The setup screen must choose a supported region, mode, and permitted radius and must show whether enough verified targets exist. Daily challenges use the chosen region's IANA time zone, allow one attempt per anonymous player per region per local day, and select a deterministic set without revealing future targets. Wider radii may reuse the curated collection and must not imply comprehensive geographic coverage.

Recommend the nearest supported region from trusted approximate Cloudflare request metadata when available. Return only the recommended region and rounded distance with private, no-store caching, and do not persist the visitor's network coordinates. If browser geolocation permission is already granted, the client may refine the recommendation automatically. Otherwise request it only after a clear user action. Compare browser coordinates to region centers entirely in browser memory; never send or store them. Permission denial, timeout, unavailable storage, and missing APIs must not block play. Store only the manually chosen region identifier in localStorage. A late location response must never override a manual choice or an active game.

During each round, show a server-proxied fixed street scene and a static map with a movable guess pin. Desktop should keep scene and map side by side within the useful viewport; phones should switch between Photo and Map in the same space while preserving state. Provide pan, zoom, center, retry, and accessible keyboard controls. The map remains visible through guess and reveal, with distinct guess and answer markers. Offer an optional clue outside daily mode and show its score penalty before use. After one committed guess, reveal the correct location, geodesic distance, score, clue effect, source attribution, and a short educational note. Finish with total score, per-round results, saved history, discovered-place notebook, and resume support.

The server is authoritative. It selects targets, returns a redacted round shape, protects future rounds, validates region bounds and coordinates, records clue use, computes WGS84 distance, scores exactly once, and ignores client-claimed scores or clue state. Use a versioned scoring profile. Supply a configurable default curve such as full credit inside a small accuracy radius, exponential decay afterward, a maximum distance cutoff, and a percentage clue penalty before final rounding. Save the rules version with every result so future scoring changes do not alter history. Use opaque UUIDs and idempotent request IDs; retries must return the committed result, and concurrent submissions must not score twice.

Implement JSON endpoints under a configurable API prefix: GET config, GET history, POST games, GET a game for resume, GET the current round scene, GET the current round map, POST clue, and POST guess. Use consistent typed error envelopes and Cache-Control headers. Require JSON content types for mutations, enforce body limits, validate same-origin Origin headers for CSRF, and reject unsupported methods, modes, radii, regions, coordinates, reused request IDs with different parameters, and access to another browser's games.

Identify an anonymous player with a high-entropy random HttpOnly, Secure, SameSite cookie. Store only its SHA-256 digest in D1. Explain that clearing the cookie disconnects the browser from saved history. Do not claim accounts or cross-device sync. Expire games, results, and notebook data after a documented interval such as 90 days. Use short-lived daily, IP-derived rate-limit hashes rather than raw IP addresses, and expire them after a small number of days. Include privacy export/deletion seams even if the anonymous first release exposes only a delete-this-browser flow.

Create numbered D1 migrations for games, rounds, panorama references, and usage counters. Games need ID, player digest, idempotent start key, region, mode, radius, local day key, and creation time, with a partial unique daily-attempt index on player, region, and day. Rounds need game ID, ordinal, internal target ID, clue flag, committed result JSON, and uniqueness by game and ordinal. Panorama storage may contain only provider panorama identifiers and last-checked times, never image bytes. Usage buckets need atomic count and expiration fields. Add foreign keys and indexes for player history and cleanup. Build migrations additively and preserve saved games across catalog or multi-region changes.

Use an independently curated and legally sourced target catalog with explicit attribution records. OpenStreetMap may be used as a source under its attribution and ODbL obligations; it is not a runtime geocoding dependency unless explicitly implemented. Validate every target before release: inside region bounds, correct type, unique stable ID, acceptable scene availability, appropriate camera distance, sensible heading, attribution, and enough density for every advertised mode/radius. Never fabricate claims of citywide coverage. Separate synthetic fixtures from the live catalog.

Required external services for the complete production implementation are Cloudflare Workers for API and static delivery, Cloudflare D1 for state and atomic quotas, Cloudflare scheduled triggers for expiry, a Git-connected Cloudflare Workers Builds pipeline, Google Street View Static API for scenes, Google Maps Static API for maps, and OpenStreetMap attribution/data licensing when its data is used. Browser Geolocation, Web Crypto, cookies, and localStorage are platform APIs rather than accounts. An optional Google Maps URL-signing secret can sign image requests. Cloudflare observability is optional but recommended. R2, a CDN image cache, service-worker image cache, analytics, accounts, leaderboards, advertising, subscriptions, native billing, matchmaking, and Postgres/PostGIS are not part of the initial build unless selected by the customization brief.

Proxy Google image calls through the Worker so the API key never reaches browser JavaScript. Enable both Street View Static API and Maps Static API on the Google Cloud project. Server-side requests require API restrictions compatible with those APIs; browser-referrer-only restrictions are inappropriate. Use Street View metadata to verify availability and refresh missing panorama IDs from source coordinates. Apply mode-specific search radii and reject cameras beyond configured distances. Preserve all provider attribution in the delivered image and add a legible textual Google Maps label where policy requires it. Stream bytes with private, no-store and explicit CDN no-store behavior. Do not persist or cache Google image bytes in D1, R2, disk, CDN, service worker, or browser application caches.

Control cost with atomic D1 reservations. Configure limits for combined Google images per UTC day, images per player/day, images per IP-derived hash/day, game starts per player/day, game starts per IP hash/day, and API calls per IP hash/minute. Fail closed if counters cannot be reserved. Failed provider requests may consume a reservation to prevent retry abuse. Avoid extra image calls when a user moves a pin or reveals an answer in the existing map viewport. Document that application counters are not Google billing caps and instruct operators to set Google Cloud project quotas and billing alerts too.

Document only secret names and bindings. Use LOCAL_GAME_DB for D1, GAME_GOOGLE_MAPS_API_KEY for the server secret, optional GAME_GOOGLE_MAPS_URL_SIGNING_SECRET, and GAME_IMAGE_DAILY_LIMIT for the configurable global budget, or derive equally generic names consistently. Local credentials belong in ignored .env or .dev.vars files. Never commit or print credentials, database IDs, signed URLs, raw addresses, player cookies, IP values, or production coordinates. Ensure errors and observability redact query strings because signed provider URLs can contain credentials.

Use these official setup references in the README and explain the relevant configuration steps:
- Cloudflare Workers: https://developers.cloudflare.com/workers/
- Cloudflare D1: https://developers.cloudflare.com/d1/
- D1 migrations: https://developers.cloudflare.com/d1/reference/migrations/
- Workers Builds: https://developers.cloudflare.com/workers/ci-cd/builds/
- Scheduled handlers: https://developers.cloudflare.com/workers/runtime-apis/handlers/scheduled/
- Google Street View Static API: https://developers.google.com/maps/documentation/streetview/overview
- Street View metadata: https://developers.google.com/maps/documentation/streetview/metadata
- Street View policy: https://developers.google.com/maps/documentation/streetview/policies
- Maps Static API: https://developers.google.com/maps/documentation/maps-static/overview
- Google URL signing: https://developers.google.com/maps/digital-signature
- Google Maps pricing: https://developers.google.com/maps/billing-and-pricing/pricing
- OpenStreetMap copyright and attribution: https://www.openstreetmap.org/copyright
- Browser Geolocation API: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

Create a local adapter with the same transaction and uniqueness behavior as D1. Include scripts for start, watch mode, unit tests, full verification, catalog validation, and live HTTP smoke testing. Automated tests must mock provider metadata and image bytes, never consume paid requests or real daily attempts. Cover scoring boundaries, projections, deterministic daily selection, region-local dates, catalog filtering, daily uniqueness, clue penalties, cookie isolation, CSRF, idempotent starts and guesses, concurrent submissions, future-round redaction, invalid pins, region bounds, image reservation/commit/release behavior, request budgets, panorama-only persistence, cleanup, and failures when credentials are absent.

Add Playwright coverage at narrow phone, tablet, short laptop, and desktop sizes. Test photo/map switching, viewport fit, keyboard pin controls, clue flows, all result states, history and resume, manual region priority, previously granted geolocation, denial and timeout, late-location race handling, and storage failure. Mock the API and imagery so layout tests are deterministic and free. Add a separate explicitly invoked test-mode or low-budget smoke script that checks real image content type, byte size, no-store headers, attribution, one complete game, and persistence without exposing response URLs or secrets.

For deployment, keep a canonical Worker name and explicit environment mapping so secrets and migrations cannot target a similarly named Worker. Export or copy an allowlist of browser assets, Worker modules, and numbered migrations into the host application; exclude secrets, local databases, build artifacts, and local servers. Run source verification, host integration tests, and the production Worker build. Apply versioned D1 migrations to the correct remote database before dependent code. Publish through the Git-connected Workers Builds pipeline rather than an undocumented local deployment. Wait for the intended production build, then verify public config, real image attribution, one controlled three-round flow, history, scheduled cleanup configuration, rate-limit metrics, and redacted logs.

Use backward-compatible migrations and roll forward for schema errors. Do not drop D1 tables or restore an old database over newly earned results as a routine rollback. If a new region or catalog schema has produced saved games, preserve readers for those records even if new starts are temporarily disabled. Catalog updates must not invalidate in-progress games: save stable target IDs and either retain historical entries or snapshot the reveal fields needed to finish them.

Include privacy and terms pages that clearly explain anonymous cookies, retention, approximate network recommendation, optional browser location, Google image requests, Cloudflare processing, OpenStreetMap attribution, and the absence of accounts or public ranking. Add a service inventory table marking every service as required, optional, planned, alternative, or explicitly absent, with setup owner, credential/binding names, billing and quota risk, local mock, health check, data handled, retention, and rotation/removal steps.

Future commerce must remain clearly separated. If requested later, Stripe web subscriptions should use hosted Checkout, verified idempotent webhooks, server-side Price allowlists, Customer Portal, and authoritative reconciliation. Apple or Google native billing, ads, sponsors, household plans, authenticated accounts, cross-device sync, and rated multiplayer are planned possibilities only. Do not add their SDKs, credentials, consent claims, or UI in this initial release.

Finish with a maintenance runbook covering catalog audits, panorama revalidation, API quota and spend review, D1 size and cleanup, cron health, rate-limit tuning, dependency updates, secret rotation, attribution and provider-policy review, backup/export strategy, incident response, privacy deletion, and quarterly restore drills. Clearly distinguish implemented behavior, operator setup, and future ideas throughout the documentation.`;
