import "server-only";

export const discordBotPrompt = `Build a production-ready, multi-server Discord automation and data bot in Python, tailored to my app brief. Support custom commands, scheduled workflows, reliable alerts, optional AI responses, and the external data sources my idea needs. The commerce-monitoring modules below are an optional worked example of a complex bot, not a requirement to build a shopping bot. Apply the same architecture to my chosen use case; keep unrelated modules disabled. Treat this as a clean-room implementation: invent neutral names, sample data, thresholds, copy, and visual styling. Do not copy any existing private bot, proprietary prompt, retailer list, identifiers, credentials, saved products, or business-specific behavior.

PRODUCT ADAPTATION: The customer brief and reviewed app specification take precedence over product examples in this foundation. Preserve an explicitly supplied original name, platform and requirements. Derive commands, roles, workflows and data sources from the brief. The pipeline and commerce scanners below are reusable examples, not a requirement to build a commerce bot. Omit scheduling, AI, scraping providers and paid data sources when unnecessary. Keep permission checks, durable operations, rate limits, setup and recovery for the systems actually enabled.

Use Python 3.12, asyncio, discord-py-interactions, Pydantic, PyYAML, Requests or HTTPX, and SQLite. Organize the project as a small application rather than one large script. Create an application entry point, typed configuration loader, Discord command package, domain services, provider adapters, persistence layer, background-job supervisor, delivery worker, tests, migrations, deployment files, and operator documentation. Keep domain rules independent from Discord objects and HTTP clients so tests can use fakes.

The core service is Discord. Explain how the owner creates an application and bot at https://discord.com/developers/applications, enables only the privileged intents actually required, generates an invite with bot and applications.commands scopes, and supplies guild, channel, and role identifiers. Use https://docs.discord.com/developers/quick-start/getting-started as the official account and installation reference while keeping the implementation in Python. Authenticate administrators by immutable Discord user or role IDs, never usernames. Register slash commands with clear permissions and ephemeral error responses. Include a generated help command whose output comes from the same command metadata, so help cannot drift when commands change.

Before building integrations, ask which data sources I want, what the bot should read or change, how often data should refresh, and which server members may see each result. Support owner-selected REST or GraphQL APIs, databases, Google Sheets or other documented spreadsheet APIs, CSV/JSON files, RSS/Atom feeds, and signed webhook events through separate adapters. These are connection options, not mandatory services or a promise that every source has a usable API. Verify each selected source's official documentation, access method, permissions and limits. When access is unavailable, explain the exact blocker and offer an owner-provided export or another documented route; do not fabricate a working connection.

Define an adapter contract for configuration validation, a read-only connection check, supported capabilities, fetching or querying records, pagination or incremental cursors, and normalized output. Preserve source name, record ID, timestamp, evidence link where available, and guild/access scope. Implement the real adapters selected in my brief, a fake adapter for offline tests, and a documented example showing how to add another source later. Keep credentials separate per source and owner; every query, cache and delivery must enforce the requesting guild and member permissions. Use parameterized database queries with a read-only account by default, bounded queries and row limits; do not execute SQL invented by an AI. Validate file types, schemas and size limits. Allow only explicitly configured network destinations and authorized database connections, never arbitrary member-supplied URLs. For push events, require authenticated HTTPS ingress, signature/replay checks and deduplication; document the extra hosting endpoint only when that feature is enabled.

Build a reusable pipeline: collect data, normalize and validate it, apply owner-configured rules, optionally run AI, then answer a command or enqueue a notification. Persist cursors only after safely recording work, make repeated events idempotent, and show data freshness and source failures. Add configurable schedules, per-source timeouts, retry and rate budgets, backpressure, and per-guild routing. Include administrator source-status and read-only test commands, plus permission-aware search, status, and workflow start/stop commands appropriate to my idea. A new data adapter should not require rewriting commands, scheduling, AI logic or Discord delivery.

For the optional commerce-monitoring example, a product-history provider is required only when historical price features are enabled. Implement a provider interface for catalog lookup, category discovery, deal browsing, current offers, and historical averages, with Keepa as the example adapter. Link setup to https://keepa.com/#!api. Keep its API key in the environment. Apply timeouts, bounded retries with exponential backoff and jitter, rate-limit awareness, and a circuit-breaker-style health state. A failed poll must retain the last successful state and must not mark products as absent. Surface degraded providers in an administrator status command without exposing request bodies or secrets.

Support an optional marketplace catalog API adapter for search and batch item lookup. Amazon Creators API is the example; link https://affiliate-program.amazon.com/creatorsapi/docs/en-us/introduction. Separate SearchItems and GetItems credentials by marketplace and role. Model credential pools explicitly, deduplicate identical credentials, allow marketplace restrictions, enforce one-request-per-second limits where required, reserve a daily allowance atomically before every attempt, honor Retry-After, and cool down credentials after authentication or quota failures. State clearly that several keys may share one account quota. Affiliate tags are optional presentation configuration and must never be confused with API credentials.

Support optional AI through a provider-neutral interface, with OpenAI as the example, key setup at https://platform.openai.com/api-keys and implementation guidance at https://developers.openai.com/api/docs/quickstart. Let my brief choose question answering over connected data, summaries, classification, scoring, or assisted workflows. For data-backed answers, retrieve only records the member may access, cite their source and freshness, and explicitly say when evidence is missing. Treat source text and Discord messages as untrusted data, never instructions that override permissions or reveal secrets. Keep tool calls on an explicit allowlist with validated arguments and server-side authorization; external writes require a separately enabled workflow and confirmation appropriate to the action. Do not send private data to an AI provider without explaining and configuring that choice.

Keep AI credentials server-side and make the model configurable. Explain separate API billing, set owner-chosen per-user and per-guild usage limits, cap input/output size and concurrency, enforce deadlines, and provide a pause switch. Require structured validated output for machine-consumed classifications and scores, including reason codes, confidence and model metadata. Preserve input order during finalization and define deterministic fallback behavior when AI is unavailable. Prompts and thresholds belong in versioned configuration. Never log full model payloads by default. The bot's commands, source lookups and non-AI workflows must remain useful when AI is disabled or its budget is exhausted.

Implement these commerce feature modules when selected. First, a general deal browser that polls each configured marketplace independently, validates current offers and seller or fulfillment constraints, compares the current price with historical statistics, deduplicates candidates, optionally applies AI scoring, and routes accepted results to configurable Discord tiers. Second, a target-price tracker with add, remove, list, pause, resume, and status commands; per-product marketplace, target, fulfillment policy, poll cadence, last state, last price, and notification references; and clear state transitions for above target, qualifying, unavailable, and stopped. Third, a category scanner that imports a documented CSV schema, allows administrators to enable or disable nodes, persists round-robin cursors, and resumes only jobs that were explicitly enabled.

For selected scanning modules, add two reusable scan strategies. An adaptive strategy first measures category volume, divides a price interval, recursively splits overloaded ranges, and persists the stable range plan. A fixed strategy divides a known or estimated population into equal price ranges and reports likely misses where the provider result cap is exceeded. Add an optional cross-market comparison strategy: search one source market, deduplicate product and exact variation identifiers, batch foreign-market lookups concurrently, normalize currency, VAT basis, shipping, condition, and pack size, calculate a candidate-excluded median, then apply savings and historical-price gates. Missing markets must reduce confidence explicitly rather than silently falling back to another credential.

Separate discovery from delivery with a durable SQLite outbox. Store destination, payload, priority, attempt count, next-attempt time, provider message ID, and an idempotency key. Reserve queue capacity for high-value alerts, combine low-value rejection diagnostics into bounded summaries, apply backpressure when full, and retry transient failures exponentially. Document at-least-once semantics and the small possibility of duplicate posts after ambiguous Discord responses. Make message formatting pure and testable. Include the relevant source, evidence, timestamps and reason codes; for commerce alerts also include product image, price evidence, marketplace and affiliate-safe links, but avoid automatic checkout actions. Restrict allowed Discord mentions so imported content cannot trigger mass notifications.

Provide optional adapters behind explicit feature flags. One may ingest public deal-community feeds through Apify, configured through https://console.apify.com/, using owner-selected actors and URLs, a polling interval, billing-error handling, and a thirty-day seen-item cache. Do not hardcode private actors or retailer searches. Another may publish accepted deals to an owner-controlled HTTPS endpoint using an environment-only high-entropy shared secret, timestamped HMAC-SHA256 signatures, replay-window validation, retries, and an idempotency key. Downstream failure must never undo or delay Discord delivery. Do not introduce services outside the owner's selected inventory.

Use SQLite migrations and transactions. Define core tables for guild settings, source configuration and access policies, source cursors, normalized records, enabled workflows and runs, credential usage and health, AI usage budgets, audit events, and the delivery outbox. Add tables for category catalog, tracked products, observed offers, product-price cache, scan counters, points totals and ledger, or seen external deals only for selected modules. Enable WAL where safe, use busy timeouts, make every write path explicit, and keep timestamps in UTC. Store only operational state in the database; secrets remain in environment variables or a secret manager. Provide backup and restore instructions that preserve databases and configuration as a matched set.

Configuration must be layered and validated: a committed example file contains non-secret behavior defaults and placeholders; environment variables contain tokens and keys; per-guild database records contain channel and feature settings. Reject missing required values at startup with concise messages. Redact values whose names imply token, key, secret, password, webhook, authorization, or credential. Never print environment dumps. Include feature-capability checks so a partially configured optional module is disabled with an actionable status instead of producing misleading results.

Create commands for help, health, source/provider status, current jobs, and an administrator-only dry-run evaluation. Add ask and summarize commands when AI is selected, and register start/stop scanner, scanner timings, categories, category import/toggle and tracker management only for enabled commerce modules. If points and rewards are enabled, add balance, monthly and all-time leaderboards, an append-only adjustment ledger, and administrator redemption. Use autocomplete where useful, defer long interactions, paginate large output, and restrict destructive or expensive operations. Every command mutation must be auditable with actor ID, guild ID, action, and timestamp.

Supervise all background tasks. Prevent duplicate startup on gateway reconnect, name tasks, report crashes, and restart only safe loops with bounded backoff. Use a single-instance lock for the default SQLite deployment and explain that this design permits one process only. For horizontal scaling, require a deliberate migration to PostgreSQL, distributed leases, a shared queue, and idempotent workers. Handle SIGINT and SIGTERM by stopping discovery, allowing a short outbox drain, flushing state, closing HTTP sessions and the gateway, and releasing locks.

Add operator-focused observability without introducing a hosted monitoring dependency. Emit structured JSON logs with severity, subsystem, guild, source, workflow/run ID, duration, result counts, retry class, and correlation ID. Hash or omit record content where it is not needed. Provide counters for successful and failed source reads, provider latency, budget remaining, records at each pipeline stage, queue depth, oldest queued message, delivery retries, and last successful workflow. Add marketplace, scan identifiers and commerce-specific counters only for enabled commerce modules. Expose status through an administrator command and an optional localhost-only health endpoint. Define warning thresholds and a short incident playbook for provider outage, quota exhaustion, corrupt state, disk pressure, Discord permission loss, and runaway retry volume. Rotate logs and prune diagnostic events, while retaining the durable audit ledger according to an owner-configured policy.

Include maintenance tools that default to dry-run: database integrity check, migration status, stale-job report, outbox inspection and replay by explicit row ID, expired-cache pruning, credential capability report, and sanitized configuration summary. Never offer a command that dumps tokens or raw configuration. Require confirmation for bulk state deletion, export records in a neutral documented format, and log every repair. Add a clock-skew check because quota windows, retry scheduling, monthly points, and signed webhooks depend on reliable UTC time.

Ship a requirements file with pinned compatible versions, a sample configuration, database migration command, systemd unit and optional Dockerfile. Write SETUP.md for someone with no coding experience, in numbered milestones: (1) install Python from https://www.python.org/downloads/ and verify its version; (2) create the folder and virtual environment and install the supplied dependencies; (3) create the Discord application, save its token privately, and invite it to a test server; (4) configure channels and roles, run migrations and tests, and verify the first help command; (5) connect each chosen data source and show a read-only probe with its expected result; (6) connect the chosen AI provider, set a budget and test an answer plus disabled/quota-exhausted behavior; (7) test the complete data-to-command or data-to-alert workflow; (8) choose a compatible host and start the bot under a supervisor; (9) check restart recovery, backups and ongoing costs. Skip optional milestones only when the corresponding feature is explicitly disabled, and respect the selected manual or computer-control working mode.

For every service, give a verified direct official account/setup URL, the exact page/action and command or complete file content, credential variable names and private storage location, the expected visible result, and a common error with its fix. For Google Sheets, begin with https://developers.google.com/workspace/sheets/api/quickstart/python, then select authentication appropriate to the owner's unattended deployment and document access to only the intended spreadsheet. Verify equivalent official setup pages for every other chosen source and host; do not leave generic "connect your API" instructions. Explain recurring charges, quotas, credential rotation, revoking a source, and how to pause scheduled and AI work. Create SERVICES.md and OPERATIONS.md with the exact selected connections and simple daily/weekly checks, including where to view logs, restart, update, back up and restore the bot. Keep the follow-up prompt guide linked from README.md.

Use a dedicated unprivileged OS account, a writable persistent data directory, restart-on-failure, log rotation, and outbound HTTPS access. The default gateway bot needs no public inbound port; an explicitly selected inbound webhook module needs separately configured authenticated HTTPS ingress. Explain upgrades: stop cleanly, back up databases and configuration, deploy source, install dependencies, run forward migrations, start, verify health and one dry-run, then retain the previous artifact for rollback.

Test with pytest or unittest and injected fakes. Cover configuration redaction and validation, command permissions, cross-guild data isolation, adapter contracts and pagination recovery, malformed files/events, webhook replay, untrusted source text in AI context, AI budget limits and fallback, reconnect idempotency, retry schedules, rate budgets under concurrency, credential cooldowns, enabled category cursors, adaptive splitting, exact variation matching, normalization, cache decisions, outbox priority and saturation, duplicate delivery, provider timeouts, restart recovery, enabled tracker transitions, migration from an older schema, and graceful shutdown. Keep all live API tests opt-in and clearly labelled; normal CI must be offline and deterministic. Add linting and type checking.

Finish with concise README sections for architecture, required services, optional services, local setup, Discord setup, provider setup, commands, configuration reference, testing, deployment, backup and restore, incident response, privacy, and cost controls. Clearly distinguish what automated tests prove from live Discord, marketplace, AI, and billing validation. Include a troubleshooting matrix for invalid intents, command propagation, missing channel access, database locks, exhausted quota, repeated alerts, stalled outbox rows, and clock skew affecting signed webhooks.`;
