import "server-only";

export const mobileAppPrompt = `Build a production-quality native iPhone app in SwiftUI, with a polished Apple-style interface, concise onboarding, and complete account, subscription, and notification flows for the modules selected in the brief. Create an original generic product, copy, visual identity, bundle identifiers, backend namespace, and sample data. Do not copy an existing private application's name, records, identifiers, exact business logic, pricing, URLs, credentials, or proprietary provider behavior. Target iOS 17 or newer unless the requirements specify another supported floor; use native Liquid Glass on supported systems with an availability-gated fallback. The result must launch in a useful, clearly labeled local demo mode without external accounts, while keeping demo state, sessions, purchases, notifications, analytics, and network traffic isolated from real users.

PRODUCT ADAPTATION: The customer brief and reviewed app specification take precedence over product examples in this foundation. Preserve an explicitly supplied original name, platform and requirements. Content feeds, libraries, rules, imports and subscriptions below are optional example modules. Choose navigation and domain models around the actual task. For people-and-meetup products, model profiles, skills, places, memberships, availability and consented invitations; specify visibility, reporting/blocking and location privacy. Gym membership claims are self-reported unless an authorized verification integration is selected. Messaging, push alerts and guest-pass rules need explicit scope decisions. Do not add a content feed or paywall merely because the foundation describes one.

Begin with an architecture decision record, API contract, privacy inventory, threat model, and a feature-status matrix marking Core, Optional, Implemented, Placeholder, and Requires external setup. Use SwiftUI with a small composition root, an observable application model, protocol-based services, async/await, and value-type domain models. Keep views declarative and move networking, persistence, authentication, purchase, notification, deep-link, and import logic into dedicated actors or services. Choose one concrete provider for each enabled concern and keep optional adapters removable. Do not force subscriptions, AI, social login, community linking, affiliate commerce, content import, or push alerts into products that do not need them.

NATIVE SCREENS AND APP STRUCTURE
Deliver actual SwiftUI screens and reusable components, with a screen map that names each screen's entry points, primary action, data source, permission or entitlement requirement, and loading, empty, error, offline, and success states. For a content-oriented service, adapt this shell: Welcome, Tailoring, Home or Discover, Browse or Search, Detail, Saved or Library, Alerts, Profile, and Membership. Remove or rename irrelevant destinations around the customer's main task. Use a native TabView for the small set of primary destinations, a NavigationStack with typed routes per tab, and system sheets for focused tasks. Preserve tab selection, navigation paths, scroll position, search and filter state on return. Keep normal back gestures and dismiss controls, honor keyboard and safe-area insets, and adapt to large text and supported iPad widths. A purchase or sign-in sheet must return to the action that opened it without discarding the user's work.

Give the main screen a clear title, one useful primary action, and a concise preview of the customer's real workflow. Content apps can use an editorial hero, compact image cards, category chips, persistent search, sorting and filters; people-oriented apps should use profiles, availability and invitations instead. Detail views should show the essential facts first, with a clear primary action and secondary Save or Share controls where relevant. Keep saved items usable offline, distinguish stale data from current data, provide image placeholders and retryable failures, and offer an undo for reversible removals. Avoid duplicate navigation, decorative dashboards, and onboarding or upgrade prompts that interrupt every visit.

DESIGN SYSTEM AND APPLE LIQUID GLASS
Build a small design system with semantic background, surface, primary/secondary text, accent, separator, success and error colors; Dynamic Type text styles; spacing and corner-radius tokens; SF Symbols; and reusable cards, choice rows, section headers, primary/secondary buttons, inline status, and empty/error views. Use a restrained accent for the main action and selection, generous whitespace, readable type, soft surface separation, and short action labels. Derive the palette and artwork from the customer's brief. Keep account, onboarding, subscription, and notification screens visually consistent. Use real system controls, accessible names, and selected traits; a checkmark and text must convey selection alongside color. Support light and dark appearances, Increase Contrast, Reduce Transparency, Reduce Motion, VoiceOver, right-to-left layout, and localization. Display settings and permissions should reflect the system's actual state.

Compile against a current supported SDK. Standard tab bars, toolbars, navigation and sheets should inherit Apple's current appearance. On iOS 26 and later, apply glassEffect(_:in:) sparingly to custom floating controls, using GlassEffectContainer when adjacent glass elements need coordinated rendering. Guard these APIs with #available(iOS 26.0, *); preserve the same actions and layout using standard SwiftUI Material or semantic opaque surfaces on older systems. Keep Liquid Glass in the control/navigation layer. Use readable conventional surfaces for content cards, plan comparisons, forms and long text. Prefer the regular glass variant for legibility; reserve clear glass for suitable media backgrounds. Respect system contrast/transparency preferences and remove ornamental movement under Reduce Motion. Avoid stacked glass effects, custom opaque backgrounds that obscure native glass navigation, and fake glass made from arbitrary translucent rectangles. Official references: https://developer.apple.com/documentation/technologyoverviews/adopting-liquid-glass, https://developer.apple.com/documentation/swiftui/applying-liquid-glass-to-custom-views, and https://developer.apple.com/design/human-interface-guidelines/materials.

ONBOARDING AND FIRST USE
Implement onboarding as a small explicit state machine rather than unrelated Boolean flags. Use a welcome screen with one clear value statement, a representative interactive preview, a primary start action, and an obvious Explore demo path. Show the native Sign in with Apple control at the point an account is needed; preserve useful guest access when the product permits it. A tailoring flow should ask only questions that affect the first experience: for example interests, goals, region when truly needed, and alert cadence. Use compact single/multiple-choice rows, a progress indicator, Back, and sensible defaults or Skip for optional questions. Persist the draft and completion state at the right guest/account scope, resume after interruption, and derive initial filters or rules deterministically without duplicating them on a retry.

Request notification access after the user chooses a relevant alert feature, with a plain-language benefit, a labeled sample preview, Enable notifications, and Not now. Denial must still allow onboarding to finish. Keep purchases contextual to trying premium functionality or viewing plans; reopening a completed app must not restart onboarding or automatically present a paywall to an active subscriber. Settings should offer Edit preferences or Run setup again with cancel/commit behavior that preserves existing account and subscription state. Complete the flow by opening a useful first screen and one obvious next action. Long downloads, optional permissions, referral offers and legal walls must not block that first useful experience. Official reference: https://developer.apple.com/design/human-interface-guidelines/onboarding.

Model the foundation generically. Suggested server records are Account, RefreshSession, Entitlement, ContentItem, ContentSummary, Source, SourceComponent, Revision, Snapshot, ImportJob, ImportStage, DurableOutbox, SearchSession, SearchCursor, SavedItem, Rule, DeviceToken, Delivery, Feedback, Referral, OAuthLink, AIConsent, EditProposal, IdempotencyKey, RateLimit, and Tombstone. Include only records needed by selected modules. Use opaque UUIDs, ISO-8601 timestamps, snake_case wire fields, stable error codes, bounded pagination, explicit nullability, and schema versions. The client domain model must not depend directly on database rows.

Implement local-first behavior. Manual content creation, editing, viewing, sorting, and saved items remain useful offline. Store account sessions in Keychain and ordinary preferences only in UserDefaults. Keep local caches scoped by account so signing out or switching accounts cannot expose another user's content. Use an explicit pending-operation queue with idempotency keys and retry metadata. For edits, maintain revision numbers or ETags, send expected revisions, detect conflicts, and offer a clear merge, keep-local, or accept-server resolution instead of last-write-wins data loss. Treat deletion as a tombstone that old queued work cannot resurrect.

If a Share Extension is selected, configure an App Group and shared Keychain access group. The extension must validate supported URLs or payloads, write a durable intent to the shared container before attempting network work, use a strict time and memory budget, and explain when the main app must reopen to finish. Handle signed-out, offline, repeated share, cold-launch, dismissal, and account-switch cases. Keep extension dependencies small and share domain/persistence code through a local Swift package. Official setup reference: https://developer.apple.com/documentation/xcode/configuring-app-groups.

For an online backend, use Cloudflare Workers as the API runtime and Supabase Postgres as its database (https://supabase.com/docs/guides/database/overview), or a user-specified equivalent stack. Do not install duplicate databases. A Cloudflare/Supabase implementation should expose a versioned REST API, keep the Supabase service role only in the Worker, deny direct client access with RLS and revoked grants, and use additive app-prefixed migrations. Validate authorization, ownership, request size, URLs, IDs, JSON shapes, cursors, and operation-specific limits. Hash refresh tokens at rest, rotate them atomically, use short-lived signed access tokens, and rate-limit by account plus a privacy-conscious client key. Use CORS only for actual trusted web clients.

Generate a service inventory that marks each integration Required, Optional, Alternative, Planned, or Absent. Include account owner, official setup URL, credential or binding names, where each secret lives, data handled, retention, recurring cost and quota risk, local mock, health check, rotation, and safe removal. The complete selectable inventory is Apple Developer and App Store Connect, Sign in with Apple, StoreKit and App Store Server Notifications, APNs, Cloudflare Workers/Queues/Cron, Supabase Postgres, an optional source catalog API, an optional transcript provider, YouTube Data API, OpenAI Responses, Discord OAuth/bot roles, an affiliate program, and CI. A local-only app needs none of the backend or provider accounts. Do not add all optional SDKs merely because they appear in this inventory.

Long-running imports use a transactional outbox and Cloudflare Queue. Creating an import atomically creates the placeholder item, source, job, revision, idempotency response, and outbox row. A scheduled dispatcher claims unpublished outbox rows with leases and publishes them. Queue delivery is at least once, so consumers must recheck account ownership, deletion, job state, lease token, and current revision before every write. Persist each stage independently so one successful source component survives a sibling failure. Classify provider errors as permanent, retryable, throttled, or unavailable; honor Retry-After and use bounded exponential backoff with jitter. Configure a dead-letter queue, retry limits, dashboards, and recovery commands. A daily retention job clears expired source components from primary rows, revisions, cached prompts, and derived stores. Official references: https://developers.cloudflare.com/queues/get-started/, https://developers.cloudflare.com/workers/configuration/cron-triggers/, and https://developers.cloudflare.com/workers/configuration/secrets/.

ACCOUNTS, PROFILE AND SETTINGS
Authentication is optional. If selected for an iPhone-only app, implement Sign in with Apple using AuthenticationServices and the system-provided sign-in button. Send the authorization code and identity token to the backend, bind the request to a fresh nonce, and validate issuer, audience, signature, expiry, nonce, and subject server-side. Exchange the code on the server when required, store Apple's refresh token encrypted, and use the stable provider subject as identity. Capture a supplied name/email when first returned; returning sign-ins may omit them. Respect private relay addresses. Separate guest, demo, signing-in, authenticated, refreshing, expired-session and deleting-account states. A canceled sign-in returns quietly to the previous screen; a failed sign-in gives an inline retry and preserves the draft. Keep Apple private keys, backend signing keys, and service-role keys out of the app. Create a separate, scoped reviewer path only if App Review requires access; credentials stay server-side and can be rotated. Official references: https://developer.apple.com/sign-in-with-apple/ and https://developer.apple.com/help/account/capabilities/create-a-sign-in-with-apple-private-key.

Build a real Profile/Settings screen with a compact account header and grouped sections: Membership, Preferences, Notifications, Account, and Help/About, including only enabled features. Show sign-in method, editable product-relevant profile fields, current plan and billing status, Restore purchases, Manage subscription, notification preferences, privacy/terms/support links, app version, Sign out, and Delete account where applicable. Every toggle and edit must persist and affect the actual service; display pending sync, a retry, or an unavailable state instead of decorative controls. Use progressive disclosure for infrequent settings and keep account recovery and subscription management easy to find.

Sign-out revokes the server session, clears Keychain credentials and account-scoped caches, detaches this installation's push registration, cancels in-flight account work, clears private navigation state and delivered notifications, and returns to a useful signed-out screen. Reject late callbacks from the previous account with a session generation or equivalent guard. Account switching and reinstall/restore must never transfer private data or entitlements to an unrelated account. Allow retryable cleanup when offline while immediately hiding the signed-out account's private data. Provide an authenticated, discoverable deletion flow with clear consequences, confirmation, progress and recovery from interrupted requests. Delete or tombstone the account's data and queued work, revoke sessions and linked provider grants, and revoke Sign in with Apple tokens using a durable retry if needed. Explain that deleting an app account does not itself cancel Apple billing, and provide subscription management without making cancellation a prerequisite for deletion. Official references: https://developer.apple.com/design/human-interface-guidelines/managing-accounts and https://developer.apple.com/support/offering-account-deletion-in-your-app/.

SUBSCRIPTION PLANS AND THE MEMBERSHIP PAGE
Subscriptions are optional. When selected, deliver the complete plan-selection screen, purchase service, entitlement model and backend verification. Define a configurable plan catalog separating access tier from billing period: a compact Standard/Pro-style pair with weekly, monthly or yearly options as chosen for this product. These are example names and intervals; specify the customer's actual benefits, limits, product IDs, subscription group and tier levels in one shared plan matrix. Billing intervals within a tier grant the same features. Put mutually exclusive tiers in one subscription group, allowlist product IDs on the server, and retain deliberately supported legacy products for restore without advertising them to new users. Any limited resource choice, such as a workspace, must be authorized and stored server-side; switching a picker cannot bypass a plan limit. A downgrade preserves user data while pausing capabilities beyond the new entitlement.

Make the membership page compact and easy to scan: a short benefit-led heading and visible Close control; a small tier/billing-period picker or grouped selectable plan rows; the selected plan's full localized billing amount and period; a few concrete included/locked benefits; one prominent purchase button; and accessible Restore purchases, Manage subscription, Terms and Privacy actions. Keep the selected state clear with a checkmark and accessible label. A native SubscriptionStoreView may provide the purchase UI where it fits; a custom SwiftUI layout must retain StoreKit's confirmation sheet. Keep the primary action reachable with safeAreaInset or a native bottom bar, let content scroll at large text sizes, and keep the billing terms adjacent and readable. Existing subscribers see their current plan and relevant management or upgrade options. Dismissing an upsell returns to available content. Show an honest locked-feature explanation at a relevant boundary rather than repeatedly blocking navigation.

Load real products with StoreKit 2 and display Product.displayPrice, the verified subscription period, and the selected product's offer terms. Only promise a free trial when the actual introductory offer is a free trial and the Apple account is eligible; derive its duration and subsequent charge from that offer instead of hardcoding a number of days. Returning or ineligible customers get accurate subscribe/upgrade wording. If a product is missing, disable that option and show Retry; never substitute another plan's price or a sample price in a live purchase flow. Label fixture prices as demo-only. A monthly equivalent for an annual plan may be secondary, with the full annual charge more prominent; calculate any savings from comparable current products in the same currency and omit unverifiable claims. Keep price loading, purchase confirmation, pending approval, cancellation, failure, restore and successful activation visibly distinct. Coalesce repeated product loads and disable duplicate purchase submissions.

SUBSCRIPTION LIFECYCLE AND ACCOUNT BINDING
For an account-backed subscription service, use a stable server-issued appAccountToken for the authenticated account. Inspect Transaction.currentEntitlements and listen to Transaction.updates from app launch. Accept only verified expected products; transmit VerificationResult.jwsRepresentation, never unsigned transaction JSON as proof, for server-backed entitlement verification. Validate the signed transaction's chain, environment, bundle, product, expiration, revocation and account binding, and bind its original transaction ID once so another account cannot claim it. Verify App Store Server Notifications V2, deduplicate transactions/notifications, and order updates so stale deliveries cannot reinstate expired or revoked access. Finish a transaction after the purchased benefit is durably delivered; if server verification is interrupted, show purchase received/verification pending, retain retry state, and recover through updates or restore without asking for another payment. Never grant access for canceled, pending or unverified purchases. A local-only app can use verified StoreKit entitlements without adding an unnecessary app account or backend; document that selected architecture and its restore behavior.

Refresh membership at sign-in, foreground return, purchase, restore and relevant server changes. AppStore.sync() belongs behind the user's Restore purchases action; routine foreground refresh must not repeatedly trigger authentication. Show the current tier, billing source, renewal or expiration date, and any pending plan change. Use StoreKit's system subscription-management flow and Apple's effective upgrade/downgrade timing. Honor verified grace-period access, billing-retry policy, cancellation at term end, refunds and revocation consistently across client and API. Treat an unreachable entitlement service as an unknown verification state, with a bounded offline policy, rather than assuming a fresh purchase is needed or creating a second subscription. If the product supports another authorized membership provider, show where that membership is managed and prevent duplicate billing. Protect every premium API route on the server, independent of local UI flags. Official references: https://developer.apple.com/documentation/storekit/subscriptionstoreview, https://developer.apple.com/documentation/storekit/verificationresult, https://developer.apple.com/storekit/, https://developer.apple.com/app-store/subscriptions/, and https://developer.apple.com/documentation/appstoreservernotifications.

NOTIFICATION EXPERIENCE AND DELIVERY
Push notifications and user-defined rules are optional. When selected, build an Alerts/Notifications screen with separate OS permission and service-connection status, Enable notifications or Open Settings as appropriate, a clearly labeled local test notification, and product-relevant rules. Rules may include interests, thresholds, cadence and quiet hours with a timezone. Provide create, edit, pause/resume and delete actions with stable IDs, versioned local persistence and idempotent server synchronization. Keep edits visible after a failed sync and show a retry. Make every cadence and quiet-hours setting affect delivery, explain any limits briefly, and distinguish a rolling delivery interval from a digest scheduled for a local time. Disable unsupported choices rather than implying they work.

Use UNUserNotificationCenter authorization and a notification delegate; refresh settings when returning to the foreground. Permission granted, APNs device registration, and successful server registration are separate states. Show denied/restricted/unavailable states without blocking the app, and never repeatedly present the system permission prompt after denial. Persist APNs environment, device token, installation/account association, locale and last-seen metadata; register token changes and permission changes safely. Sign-out, account deletion, token invalidation and account switching must revoke the previous account's delivery association. Demo previews use isolated local notifications and never register a real account or enqueue a live push. A successful local test demonstrates the presentation/tap route, not APNs delivery.

Match events against current rules on the server, enqueue deliveries transactionally, deduplicate overlapping matches for the same account/device/event, enforce quiet hours and per-user caps, and recheck permission, account ownership, rule revision, entitlement and event expiry immediately before dispatch. Use a dispatcher that supports APNs HTTP/2, keep APNs signing keys in its secret manager, and handle token invalidation, throttling, bounded retries, leases and expiration. Do not promise guaranteed or immediate delivery. Derive the APNs topic/environment from the signed build configuration and matching server settings. Send only minimal opaque routing identifiers and safe preview text, never private free text or arbitrary executable/external URLs.

Register notification categories and useful actions. Merely receiving a push must not navigate or open another app. Route a deliberate tap through a typed deep-link coordinator; preserve a pending destination across cold launch or required sign-in, then revalidate its account, identifiers, entitlement and current content before opening it. Expired, deleted or inaccessible targets get a clear recoverable in-app state. If the product supports external handoff, build an allowlisted HTTPS destination from validated data and require a user action. Prefer subtle in-app updates for foreground events, keep unread badges accurate, and avoid duplicate banners for content already visible. A trial-ending reminder, if requested, uses the verified entitlement end date, follows notification permission, and is rescheduled or removed after entitlement changes. Official references: https://developer.apple.com/design/human-interface-guidelines/notifications, https://developer.apple.com/documentation/usernotifications/asking-permission-to-use-notifications, and https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns.

An optional discovery or commerce module may ingest normalized catalog events from one provider, offer feed filters, saves, historical metrics, feedback, external handoff, referrals, and geographic availability requests. Put the provider behind an adapter and keep its credential server-side. Signed internal ingestion must authenticate the timestamp and exact body, reject stale requests, enforce body limits, validate every external URL and image host, and upsert on a stable natural key. External handoff links must be generated server-side when formats or attribution rules can change, display required affiliate disclosures, and let the external app or browser complete the transaction. Do not automate third-party checkout or promise availability the provider cannot guarantee.

If the selected product is a retail deal feed, Keepa may be used as the optional catalog and price-history adapter; document its account and token quotas at https://keepa.com/#!api. Amazon Associates may be used only for compliant attributed outbound links, with current program terms and disclosure guidance at https://affiliate-program.amazon.com/help. These are examples, not required dependencies, and neither credential belongs in the app. The current feed request path should use stored normalized scores; an AI scorer is a separate optional ingestion-stage provider and must not silently become a request-time dependency.

An optional source-to-structured-content module may accept a shared URL, capture independent source components such as description and timed captions through approved provider APIs, and transform them into a user-owned structured draft. Record provenance, capture status, expiry, and rights for each component. Search should use server-side sessions with opaque expiring cursors, return small pages, and consume buffered provider results before making another paid call. Never scrape around provider restrictions or claim permanent rights to source content.

For a video-source implementation, use the YouTube Data API through a server adapter and follow https://developers.google.com/youtube/v3/getting-started. A transcript vendor such as TranscriptAPI is an optional second adapter; use its current provider documentation at https://transcriptapi.com and verify terms, supported caption types, retention, credits, and failure behavior before enabling it. Keep description and caption acquisition independently observable so one can succeed when the other is unavailable. Both keys remain server-side, and the module must remain disabled rather than scrape when authorized providers are absent.

AI assistance is optional and requires explicit, versioned consent. Use a server-side OpenAI Responses adapter with a configured model, structured JSON output, narrow prompts, and store:false. Send only the current item, scoped request, revision, and necessary source material; never send account tokens, unrelated library history, or hidden personal data. A missing provider must leave manual editing operational and return a clear unavailable status, never fabricated output. Generate an EditProposal containing bounded patches against an expected revision. Show a diff and require user acceptance before applying it. Reserve the idempotency key before the provider call so retries or lost acknowledgments replay one proposal instead of incurring another call. Recheck consent and revision inside the final transaction. Official references: https://developers.openai.com/api/docs/guides/structured-outputs and https://developers.openai.com/api/docs/guides/your-data.

Optional community OAuth should use ASWebAuthenticationSession, short-lived one-time state, PKCE where supported, exact redirect URI matching, and a backend token exchange. Store only the minimum durable link; revoke transient OAuth tokens after reconciliation when possible. Role or membership checks must fail closed, expire quickly, and never let ordinary community membership impersonate a paid entitlement. Disconnect removes the app-managed grant without deleting the external account.

If Discord is selected for community access, configure the application, redirect URI, bot, guild, and app-managed role using https://discord.com/developers/applications and https://docs.discord.com/developers/platform/oauth2-and-permissions. Request only required scopes and permissions, keep the bot token server-side, place the bot role above every app-managed role in the server role hierarchy, reconcile access after entitlement changes, and test new-member, existing-member, disconnect, expiry, screening, and provider-outage paths.

Provide a URLSession API client with request IDs, authenticated retry after one serialized token refresh, typed decoding, timeout policy, cancellation, and sanitized logging. Prevent refresh stampedes with an actor. Never log access tokens, authorization codes, transaction JWS values, provider payloads containing retained content, or full notification tokens. Enforce HTTPS outside loopback development. Separate Debug, Review, Staging, and Production configuration through xcconfig or generated build settings; no secrets in Info.plist, entitlements, source, StoreKit configuration, or committed JSON.

IMPLEMENTATION ORDER AND ACCEPTANCE
Build the design system and navigable screen shell with deterministic fixtures first, then one complete core workflow with local persistence. Add onboarding and account recovery, the selected subscription and notification modules, and only then optional providers. Each milestone must be usable end to end, with explicit unavailable states for unfinished integrations. Keep service configuration and implementation details in developer documentation; product screens should explain the user's outcome and next action. Supply a screen/state matrix and previews for welcome, tailoring, main navigation, detail, profile, every configured plan, purchase recovery, notification settings and empty/error/offline states.

Tests must cover domain validation, local persistence, account isolation, offline operation, queued replay, idempotency, cursor expiry, rate limits, stale revisions, deletion during queued work, lease fencing, partial provider failure, retention cleanup, auth rotation, Apple audience and nonce, entitlement ordering, notification deduplication, and AI proposal acceptance for enabled modules. Add URLProtocol or protocol fakes for client tests, an in-memory backend repository for deterministic route tests, and a loopback review server that exercises real routing without production services. Run Swift package tests, xcodebuild build/test for the app and any selected extension, backend typecheck/tests, and a Worker deployment dry run where applicable.

Verify these customer journeys for each enabled module:
- Complete onboarding with skipped optional questions and denied notifications, kill/reopen during setup, revisit preferences and cancel safely, and finish the first useful action. Demo exploration must remain isolated from real accounts and billing.
- Select each tier and billing period; show accurate localized prices, eligible and ineligible offer copy, unavailable-product recovery, a working Close action, and reachable restore/terms/privacy controls. Test a small phone and accessibility text sizes without hiding the price or primary action.
- Exercise canceled and pending purchases, interrupted server verification, a lost response, duplicate transaction delivery, restore after reinstall, and a second device. Confirm one purchase grants only its authorized benefits. Test renewals, grace, billing retry, expiration, refunds, upgrades, downgrades and out-of-order server events.
- Switch between two accounts while requests are in flight; verify saved data, membership, onboarding state and notifications remain scoped correctly. Test expired credentials, sign-out offline, deletion retries and revocation recovery without resurrecting private content.
- Create, edit, pause and delete notification rules, change permissions in Settings, retry failed device registration, and test quiet hours across timezone changes. Exercise foreground receipt, cold-launch taps, signed-out taps, expired content, invalid routes and duplicate delivery. Verify a local sample alert cannot mutate a live account.
- Review actual screen renders in light/dark appearances, large Dynamic Type, VoiceOver, Increase Contrast, Reduce Transparency and Reduce Motion, plus both native Liquid Glass and the older-iOS fallback. Check back navigation, sheet dismissal, keyboard overlap, scrolling under bars, selection labels and error recovery. Use synthetic screenshots from the implemented views, and keep simulator, StoreKit fixtures, TestFlight and real-provider results clearly distinguished.

Document local setup with example configuration files containing variable names only. A typical backend sequence is install dependencies, typecheck, test, run the loopback review server, perform a Worker dry-run bundle, and start local development. A typical iOS sequence is resolve packages, generate or open the Xcode project, select the development configuration, run a simulator, execute unit/UI tests, then test extensions and notifications on a physical device. Include seed fixtures that contain no real user data.

The deployment runbook must verify the target, take a database backup, review and apply additive migrations, provision the Queue and dead-letter queue if imports are enabled, add encrypted Worker/CI secrets, deploy staging, verify health and migrations, then exercise two-account isolation and failure recovery. Production promotion requires real-provider coverage, quota checks, cron and queue monitoring, Apple webhook configuration, APNs delivery, account deletion/revocation, and retention cleanup. Keep rollback artifacts and explain whether rollback also requires a database restore. Never print secret values in commands or logs.

For App Store delivery, use fresh explicit app and extension identifiers, App Group, Keychain group, Sign in with Apple, push, and IAP capabilities only when selected. Archive with the current required Xcode/iOS SDK, upload to App Store Connect, test the processed build through TestFlight on a physical iPhone, and complete privacy, age-rating, export-compliance, content-rights, support, and review-access fields. Official references: https://developer.apple.com/programs/enroll/, https://developer.apple.com/documentation/xcode/distributing-your-app-for-beta-testing-and-releases, https://developer.apple.com/help/app-store-connect/test-a-beta-version/testflight-overview/, and https://developer.apple.com/app-store/review/guidelines/.

Finish by running every available local check and report the repository tree, architecture and data-flow diagrams, exact commands to run the demo and tests, enabled optional modules, required external accounts, credential variable names without values, manual console work, migration and rollback steps, monitoring and maintenance procedures, and all unverified live checks. State plainly that local fixtures and successful builds do not prove provider coverage, push delivery, store purchases, cross-device sync, provisioning, or App Review readiness.`;
