import "server-only";

export const mobileGamePrompt = `Build a production-quality mobile game matching the brief in Godot 4.x stable. An idle RPG is the worked example below. Treat this as a reusable commercial starter, so invent an original title, setting, characters, art direction, copy, item names, identifiers, and economy. Do not reproduce any existing game's lore, balance tables, UI, assets, package names, URLs, or credentials. Use typed GDScript as the default, Android and iOS targets, landscape 16:9, responsive safe-area support, and acceptable operation on older mid-range phones. Use C# or GDExtension only for a measured bottleneck or a necessary native platform bridge. The generated repository must run in a fully local demo mode before any paid account or remote service is configured.

PRODUCT ADAPTATION: The customer brief and reviewed app specification take precedence over product examples in this foundation. Preserve an explicitly supplied original name, platform and requirements. The idle RPG loop, combat, prestige, loot and guild systems below form one optional worked example. Derive the genre, controls, orientation, progression and core loop from the brief. Omit those RPG systems for puzzle, racing, platform or other games that do not need them. Keep relevant save integrity, performance, platform integration and release safeguards, and adapt tests to the chosen mechanics.

Start by writing a short architecture decision record and a feature-status matrix with Core, Optional, Implemented, Placeholder, and Requires external setup columns. Keep domain code independent of SDKs. Put platform and vendor integrations behind narrow adapters so ads, billing, authentication, cloud storage, notifications, analytics, and backend providers can be omitted or replaced. Choose one provider per concern; do not install competing stacks. Pin Godot add-ons and native SDK versions, record licenses in an SBOM, and use placeholder bundle identifiers until the owner supplies final values.

Implement the core loop as idle resource production, optional active actions that apply bounded multipliers, upgrade purchases as currency sinks, stage progression, boss gates, prestige resets with permanent bonuses, and collectible equipment or characters. Use typed Godot Resource classes for authored definitions and validated versioned JSON for data catalogs and live configuration. Definitions need stable IDs and validation for duplicates, broken references, impossible costs, invalid probabilities, and missing localization. Keep state models separate from presentation. Use a single authoritative simulation clock with a configurable fixed tick, normally one second. UI observes signals and must not drive the economy from frame callbacks such as _process(). Compute offline gains in closed form rather than replaying every missed tick, cap the eligible duration, detect backward-clock anomalies, and show the exact calculation before the user claims it.

Build combat as deterministic mathematical simulation. Use accumulator-based attack and ability cooldowns so speed modifiers have continuous effects without frame-rate breakpoints. Keep damage, mitigation, healing, enemy scaling, loot, experience, and stage rules in typed GDScript services that can be tested without presentation scenes. Seed only non-economic local simulations. Any paid or competitive random outcome must be produced or verified by the server. Display loot probabilities and pity progress before a paid randomized purchase, and retain Python or headless-Godot simulation tooling that can run millions of pulls to compare observed and configured rates.

Use a small splash/bootstrap scene and feature scenes loaded asynchronously. Organize scripts into autoload infrastructure managers, data repositories, gameplay systems, UI/components, and tooling. Autoload only process-wide services whose lifetime and initialization order are justified: for example SaveManager, EventManager, GameClock, NetworkManager, AuthManager, CurrencyManager, content databases, and top-level gameplay coordinators. Put the exact dependency order in project.godot. Cross-feature communication goes through typed signals on one event bus or narrow interfaces, never get_node searches into unrelated systems. Avoid turning every helper into an autoload. Pool frequently spawned visual objects, stream large OGG music, use sprite sheets and atlases, keep ETC2/ASTC import settings mobile-safe, cap atlas size appropriately, and use ResourceLoader.load_threaded_request for noninitial scenes and large resources. If downloadable content is truly required, add one versioned manifest/provider rather than inventing a second content system.

Persist a versioned save envelope containing schema version, revision, timestamps, integrity metadata, and payload. Write atomically through a temporary file, keep at least three valid rolling backups, validate before deserialization, and migrate old schemas through explicit sequential migrators. Store sensitive tokens only in iOS Keychain or Android Keystore through a reviewed secure-storage adapter. Never invent homemade cryptography. If local save confidentiality is required, use a reviewed authenticated-encryption implementation, keep key material out of source and ordinary preferences, document device-transfer behavior, and test corruption, interruption, upgrade, reinstall, restore, and tamper cases. Currency mutations must pass through one ledger service with reason codes, idempotency keys, bounds checks, and auditable entries.

The base game must work offline after its first successful boot. Make online services a selectable module. If online accounts, cloud saves, social features, or competitive boards are selected, use one backend: either Supabase Auth/Postgres/Realtime/Edge Functions or a user-specified equivalent. For Supabase, create additive numbered SQL migrations, Row Level Security for every player-owned table, least-privilege grants, service-role access only on the server, rate limits, idempotency records, deletion workflows, and a maintenance-mode record. Model accounts, profiles, cloud-save revisions, entitlements, purchase transactions, mail, leaderboards, guilds, chat reports, raids, reward events, and moderation separately. Resolve cloud conflicts explicitly with revision or compare-and-swap rules; never silently overwrite newer progress. Chat and guilds are optional and require sanitization, length limits, reporting, blocking, retention rules, and moderation tools.

For every build, generate a service inventory that marks each integration Required, Optional, Alternative, Planned, or Absent. Include account owner, credential variable names, client-versus-server placement, data handled, recurring cost or quota, local stub, health check, rotation, and removal steps. For this full-feature foundation, inventory Godot, Supabase Auth/Postgres/Realtime/Edge Functions, Google Cloud OAuth, Apple Developer and App Store Connect, Google Play Console and Billing, Unity LevelPlay, Unity Ads within LevelPlay, native local notifications, and CI hosting such as GitHub Actions. Core offline play requires none of the network vendors. Do not describe analytics, crash reporting, remote content, social systems, ads, purchases, or cloud sync as enabled unless selected and tested.

Authentication is optional. Offer guest/local play and account upgrade unless the product explicitly requires online identity. For native sign-in, support Google on Android and Sign in with Apple on iOS through maintained, pinned Godot native plugins, exchange provider ID tokens with the backend, verify tokens server-side, use cryptographic nonces, rotate sessions, and never ship provider secrets. Provide editor stubs and guard every native singleton lookup so the project still runs when a platform plugin is absent. If any third-party login appears on iOS, include Sign in with Apple and follow Apple's current review rules. Account deletion must revoke sessions, schedule or perform data deletion, preserve only legally required transaction records, and explain the result to the player.

Use official setup references in the generated documentation: Supabase https://supabase.com/docs, Supabase Google auth https://supabase.com/docs/guides/auth/social-login/auth-google, Supabase Apple auth https://supabase.com/docs/guides/auth/social-login/auth-apple, Google Auth Platform https://console.cloud.google.com/auth, Apple Developer enrollment https://developer.apple.com/programs/enroll/, Google Play Console https://play.google.com/console/, and GitHub Actions https://docs.github.com/actions. Third-party Godot bridges must link their own source repository and release notes, undergo source review, and be recorded as non-official adapters rather than presented as built-in engine features.

Purchases are an optional monetization module. Use maintained, pinned Godot billing plugins for Google Play Billing and Apple StoreKit, retrieve localized product data from the stores, restore purchases, listen for unfinished transactions, and validate receipts or signed transactions on a trusted server before granting consumable currency or durable entitlements. Deduplicate by store transaction ID and deliver server-confirmed rewards through an inbox or ledger so retries cannot double grant. Include an editor fake-store adapter, Apple sandbox/TestFlight tests, Google license-tester/internal-track tests, refunds, pending purchases, reconnects, restore on a second device, and replay attempts. Never log receipts or account tokens. Official references: https://docs.godotengine.org/en/stable/tutorials/platform/android/android_in_app_purchases.html and https://developer.apple.com/storekit/.

Rewarded advertising is optional and opt-in. If selected, integrate Unity LevelPlay through a pinned native Godot bridge as the single mediation boundary and add only explicitly chosen ad networks. Keep the game's AdManager decoupled from the native singleton so editor and desktop builds parse and run without the plugin. Initialize after consent, wait for native initialization, check readiness and placement caps, and handle reward and close callbacks in either order. For an online economy, grant value only after a signed server-to-server callback is validated and its event ID is deduplicated; the client callback may update UI but must not mint authoritative currency. Apply daily caps and clear failure states. Use test mode and the vendor integration test suite on physical devices before production. Official references for the native Android/iOS SDKs and callback are https://docs.unity.com/en-us/grow/levelplay/sdk/android/sdk-integration, https://docs.unity.com/en-us/grow/levelplay/sdk/ios/sdk-integration, and https://docs.unity.com/en-us/grow/levelplay/platform/settings/server-to-server-callback. Document the bridge's exact Engine singleton and signal contract.

Local notifications are optional. Ask only after a meaningful in-game moment and only after an explanatory pre-prompt. Schedule useful events such as an offline cap or a completed timer, deduplicate requests, honor quiet hours, and provide a master setting. Do not request contacts, location, camera, microphone, tracking, or other unrelated permissions. Analytics and crash reporting are optional provider choices; the game must compile without them. If enabled, require consent where applicable, minimize event properties, exclude free text and identifiers, document retention, and make telemetry failure non-blocking.

Implement accessible, localized UI with controller/touch parity, safe-area handling, scalable text, readable contrast, reduced-motion and haptic toggles, audio buses, and battery-saver options. Separate logical resolution from physical pixels. Pause expensive rendering when backgrounded. Budget cold start, scene transitions, memory, package size, and frame time, then add profiler captures for low, representative, and high content loads. Never conceal a long key derivation, migration, or network wait behind a frozen screen.

Provide deterministic tests for economy arithmetic, offline progression, clock anomalies, stage gates, combat speed, prestige, pity, loot distributions, save migration, corruption recovery, ledger idempotency, and cloud conflict resolution. Add headless scene smoke tests for boot, navigation, background/resume, missing optional native plugins, and local demo mode. Create JSON Schema and Python validation for content IDs and references. CI must run headless parsing, GDScript tests, content validation, simulation checks, secret scanning, and Android/iOS export validation where runners support it. A release cannot rely solely on a successful Godot export.

Include README, architecture, threat model, privacy inventory, data retention, service setup, operations, and release runbooks. Use .env.example or settings templates containing names only. Gitignore keystores, provisioning profiles, platform service files, private keys, secrets.gd, generated exports, .godot caches, and local overrides. The setup guide must distinguish actions the code completed from console actions a human still owes. Link to official Godot Android and iOS export documentation, https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html and https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_ios.html, plus Apple review guidelines https://developer.apple.com/app-store/review/guidelines/ and Google target API requirements https://developer.android.com/google/play/requirements/target-sdk.

The release runbook must use separate development, staging, and production configuration. Before remote database changes, identify the target, back it up, inspect pending migrations, and apply only reviewed additive changes. Install export templates matching the exact Godot version. Build an Xcode project for iOS and an Android App Bundle for Play without printing secrets. Test on minimum, representative, and current physical devices: fresh install, upgrade, offline boot, reconnect, backgrounding, low memory, interrupted save, cloud conflict, purchase restore, notification denial, account deletion, and every enabled provider. Publish privacy policy, terms, support URL, randomized-item odds where applicable, store privacy answers, age rating, screenshots, and reviewer access. Release through TestFlight and Play internal/closed tracks, then stage production rollout with health metrics, maintenance switch, rollback artifact, and database recovery plan.

Finish by running all available local checks and presenting: repository tree, architecture diagram, commands to open and run the demo, test results, performance assumptions, enabled optional modules, every required external account and credential name without values, exact manual console steps, deployment and rollback commands with placeholders, and an honest list of checks that require real devices, store sandboxes, or production services. Do not claim an integration is live merely because its adapter compiles.`;
