import "server-only";

export const mobileAppPrompt = `Build a production-quality native iPhone service app in SwiftUI. Create an original generic product, copy, visual identity, bundle identifiers, backend namespace, and sample data. Do not copy an existing private application's name, records, identifiers, exact business logic, pricing, URLs, credentials, or proprietary provider behavior. Target iOS 17 or newer unless the requirements specify another supported floor. The result must launch in a useful, clearly labeled local demo mode without external accounts, while keeping demo state, sessions, purchases, notifications, analytics, and network traffic isolated from real users.

PRODUCT ADAPTATION: The customer brief and reviewed app specification take precedence over product examples in this foundation. Preserve an explicitly supplied original name, platform and requirements. Content feeds, libraries, rules, imports and subscriptions below are optional example modules. Choose navigation and domain models around the actual task. For people-and-meetup products, model profiles, skills, places, memberships, availability and consented invitations; specify visibility, reporting/blocking and location privacy. Gym membership claims are self-reported unless an authorized verification integration is selected. Messaging, push alerts and guest-pass rules need explicit scope decisions. Do not add a content feed or paywall merely because the foundation describes one.

Begin with an architecture decision record, API contract, privacy inventory, threat model, and a feature-status matrix marking Core, Optional, Implemented, Placeholder, and Requires external setup. Use SwiftUI with a small composition root, an observable application model, protocol-based services, async/await, and value-type domain models. Keep views declarative and move networking, persistence, authentication, purchase, notification, deep-link, and import logic into dedicated actors or services. Choose one concrete provider for each enabled concern and keep optional adapters removable. Do not force subscriptions, AI, social login, community linking, affiliate commerce, content import, or push alerts into products that do not need them.

For a content-oriented service, the following shell is an example to adapt: welcome and onboarding; a short preference or tailoring flow; contextual notification pre-prompt; navigation named for the selected workflows (for example Discover, Saved or Library, Rules or Workflows, and Profile); searchable and filterable paginated content; detail views with metadata, history and a primary external or internal action; offline-friendly saved state; settings, privacy and support, with restore purchases or account deletion only when the relevant modules are enabled. Use a coherent design system for color, type, spacing, cards, loading, empty, error, stale, and disabled states. Support Dynamic Type, VoiceOver, Reduce Motion, dark mode, keyboard navigation where relevant, safe areas, localization, and slow or lossy networks.

Model the foundation generically. Suggested server records are Account, RefreshSession, Entitlement, ContentItem, ContentSummary, Source, SourceComponent, Revision, Snapshot, ImportJob, ImportStage, DurableOutbox, SearchSession, SearchCursor, SavedItem, Rule, DeviceToken, Delivery, Feedback, Referral, OAuthLink, AIConsent, EditProposal, IdempotencyKey, RateLimit, and Tombstone. Include only records needed by selected modules. Use opaque UUIDs, ISO-8601 timestamps, snake_case wire fields, stable error codes, bounded pagination, explicit nullability, and schema versions. The client domain model must not depend directly on database rows.

Implement local-first behavior. Manual content creation, editing, viewing, sorting, and saved items remain useful offline. Store account sessions in Keychain and ordinary preferences only in UserDefaults. Keep local caches scoped by account so signing out or switching accounts cannot expose another user's content. Use an explicit pending-operation queue with idempotency keys and retry metadata. For edits, maintain revision numbers or ETags, send expected revisions, detect conflicts, and offer a clear merge, keep-local, or accept-server resolution instead of last-write-wins data loss. Treat deletion as a tombstone that old queued work cannot resurrect.

If a Share Extension is selected, configure an App Group and shared Keychain access group. The extension must validate supported URLs or payloads, write a durable intent to the shared container before attempting network work, use a strict time and memory budget, and explain when the main app must reopen to finish. Handle signed-out, offline, repeated share, cold-launch, dismissal, and account-switch cases. Keep extension dependencies small and share domain/persistence code through a local Swift package. Official setup reference: https://developer.apple.com/documentation/xcode/configuring-app-groups.

For an online backend, use Cloudflare Workers as the API runtime and Supabase Postgres as its database (https://supabase.com/docs/guides/database/overview), or a user-specified equivalent stack. Do not install duplicate databases. A Cloudflare/Supabase implementation should expose a versioned REST API, keep the Supabase service role only in the Worker, deny direct client access with RLS and revoked grants, and use additive app-prefixed migrations. Validate authorization, ownership, request size, URLs, IDs, JSON shapes, cursors, and operation-specific limits. Hash refresh tokens at rest, rotate them atomically, use short-lived signed access tokens, and rate-limit by account plus a privacy-conscious client key. Use CORS only for actual trusted web clients.

Generate a service inventory that marks each integration Required, Optional, Alternative, Planned, or Absent. Include account owner, official setup URL, credential or binding names, where each secret lives, data handled, retention, recurring cost and quota risk, local mock, health check, rotation, and safe removal. The complete selectable inventory is Apple Developer and App Store Connect, Sign in with Apple, StoreKit and App Store Server Notifications, APNs, Cloudflare Workers/Queues/Cron, Supabase Postgres, an optional source catalog API, an optional transcript provider, YouTube Data API, OpenAI Responses, Discord OAuth/bot roles, an affiliate program, and CI. A local-only app needs none of the backend or provider accounts. Do not add all optional SDKs merely because they appear in this inventory.

Long-running imports use a transactional outbox and Cloudflare Queue. Creating an import atomically creates the placeholder item, source, job, revision, idempotency response, and outbox row. A scheduled dispatcher claims unpublished outbox rows with leases and publishes them. Queue delivery is at least once, so consumers must recheck account ownership, deletion, job state, lease token, and current revision before every write. Persist each stage independently so one successful source component survives a sibling failure. Classify provider errors as permanent, retryable, throttled, or unavailable; honor Retry-After and use bounded exponential backoff with jitter. Configure a dead-letter queue, retry limits, dashboards, and recovery commands. A daily retention job clears expired source components from primary rows, revisions, cached prompts, and derived stores. Official references: https://developers.cloudflare.com/queues/get-started/, https://developers.cloudflare.com/workers/configuration/cron-triggers/, and https://developers.cloudflare.com/workers/configuration/secrets/.

Authentication is optional. If selected for an iPhone-only app, implement Sign in with Apple using AuthenticationServices and send the authorization code and identity token to the backend. Validate issuer, audience, signature, expiry, nonce, and subject server-side. Store Apple's refresh token encrypted on the server and attempt revocation during account deletion before removing its ciphertext. Keep Apple private keys, backend signing keys, and service-role keys out of the app. Create a separate, scoped reviewer path only if App Review requires access; credentials stay server-side and can be rotated. Official references: https://developer.apple.com/sign-in-with-apple/ and https://developer.apple.com/help/account/capabilities/create-a-sign-in-with-apple-private-key.

Subscriptions are optional. If enabled, use StoreKit 2, load localized products, show billing period, trial eligibility, renewal terms, cancellation path, and tier differences accurately, support restore and subscription management, and observe transaction updates continuously. Send verified transaction material and an appAccountToken to the server. Validate signed transactions and App Store Server Notifications V2, order updates so an older notification cannot overwrite a newer entitlement, deduplicate notification and transaction IDs, and make every protected API route recheck current entitlement. Support sandbox, TestFlight, refund, expiration, upgrade, downgrade, grace, billing retry, restore, and second-device tests. Do not hardcode storefront prices into eligibility logic. Official references: https://developer.apple.com/storekit/, https://developer.apple.com/app-store/subscriptions/, and https://developer.apple.com/documentation/appstoreservernotifications.

Push notifications and user-defined rules are optional. Ask permission only after explaining a concrete benefit. Persist APNs environment, device token, account, locale, and last-seen metadata; rotate and revoke tokens safely. Match incoming events to normalized rules on the server, enqueue deliveries transactionally, deduplicate by account/event/rule, enforce quiet hours and per-user caps, and recheck membership immediately before dispatch. Notification actions and deep links must validate IDs and fetch current state; stale or expired content gets a safe in-app explanation. Never put secrets or sensitive free text in payloads. Use a separate dispatcher with APNs signing keys stored only in its secret manager. Official reference: https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns.

An optional discovery or commerce module may ingest normalized catalog events from one provider, offer feed filters, saves, historical metrics, feedback, external handoff, referrals, and geographic availability requests. Put the provider behind an adapter and keep its credential server-side. Signed internal ingestion must authenticate the timestamp and exact body, reject stale requests, enforce body limits, validate every external URL and image host, and upsert on a stable natural key. External handoff links must be generated server-side when formats or attribution rules can change, display required affiliate disclosures, and let the external app or browser complete the transaction. Do not automate third-party checkout or promise availability the provider cannot guarantee.

If the selected product is a retail deal feed, Keepa may be used as the optional catalog and price-history adapter; document its account and token quotas at https://keepa.com/#!api. Amazon Associates may be used only for compliant attributed outbound links, with current program terms and disclosure guidance at https://affiliate-program.amazon.com/help. These are examples, not required dependencies, and neither credential belongs in the app. The current feed request path should use stored normalized scores; an AI scorer is a separate optional ingestion-stage provider and must not silently become a request-time dependency.

An optional source-to-structured-content module may accept a shared URL, capture independent source components such as description and timed captions through approved provider APIs, and transform them into a user-owned structured draft. Record provenance, capture status, expiry, and rights for each component. Search should use server-side sessions with opaque expiring cursors, return small pages, and consume buffered provider results before making another paid call. Never scrape around provider restrictions or claim permanent rights to source content.

For a video-source implementation, use the YouTube Data API through a server adapter and follow https://developers.google.com/youtube/v3/getting-started. A transcript vendor such as TranscriptAPI is an optional second adapter; use its current provider documentation at https://transcriptapi.com and verify terms, supported caption types, retention, credits, and failure behavior before enabling it. Keep description and caption acquisition independently observable so one can succeed when the other is unavailable. Both keys remain server-side, and the module must remain disabled rather than scrape when authorized providers are absent.

AI assistance is optional and requires explicit, versioned consent. Use a server-side OpenAI Responses adapter with a configured model, structured JSON output, narrow prompts, and store:false. Send only the current item, scoped request, revision, and necessary source material; never send account tokens, unrelated library history, or hidden personal data. A missing provider must leave manual editing operational and return a clear unavailable status, never fabricated output. Generate an EditProposal containing bounded patches against an expected revision. Show a diff and require user acceptance before applying it. Reserve the idempotency key before the provider call so retries or lost acknowledgments replay one proposal instead of incurring another call. Recheck consent and revision inside the final transaction. Official references: https://developers.openai.com/api/docs/guides/structured-outputs and https://developers.openai.com/api/docs/guides/your-data.

Optional community OAuth should use ASWebAuthenticationSession, short-lived one-time state, PKCE where supported, exact redirect URI matching, and a backend token exchange. Store only the minimum durable link; revoke transient OAuth tokens after reconciliation when possible. Role or membership checks must fail closed, expire quickly, and never let ordinary community membership impersonate a paid entitlement. Disconnect removes the app-managed grant without deleting the external account.

If Discord is selected for community access, configure the application, redirect URI, bot, guild, and app-managed role using https://discord.com/developers/applications and https://docs.discord.com/developers/platform/oauth2-and-permissions. Request only required scopes and permissions, keep the bot token server-side, place the bot role above every app-managed role in the server role hierarchy, reconcile access after entitlement changes, and test new-member, existing-member, disconnect, expiry, screening, and provider-outage paths.

Provide a URLSession API client with request IDs, authenticated retry after one serialized token refresh, typed decoding, timeout policy, cancellation, and sanitized logging. Prevent refresh stampedes with an actor. Never log access tokens, authorization codes, transaction JWS values, provider payloads containing retained content, or full notification tokens. Enforce HTTPS outside loopback development. Separate Debug, Review, Staging, and Production configuration through xcconfig or generated build settings; no secrets in Info.plist, entitlements, source, StoreKit configuration, or committed JSON.

Tests must cover domain validation, local persistence, account isolation, offline operation, queued replay, idempotency, cursor expiry, rate limits, stale revisions, deletion during queued work, lease fencing, partial provider failure, retention cleanup, auth rotation, Apple audience and nonce, entitlement ordering, notification deduplication, and AI proposal acceptance. Add URLProtocol or protocol fakes for client tests, an in-memory backend repository for deterministic route tests, and a loopback review server that exercises real routing without production services. Run Swift package tests, xcodebuild build/test for app and extension, backend typecheck/tests, and a Worker deployment dry run. UI tests should cover onboarding, demo isolation, accessibility labels, deep links, purchase gates, offline edits, sharing, and deletion.

Document local setup with example configuration files containing variable names only. A typical backend sequence is install dependencies, typecheck, test, run the loopback review server, perform a Worker dry-run bundle, and start local development. A typical iOS sequence is resolve packages, generate or open the Xcode project, select the development configuration, run a simulator, execute unit/UI tests, then test extensions and notifications on a physical device. Include seed fixtures that contain no real user data.

The deployment runbook must verify the target, take a database backup, review and apply additive migrations, provision the Queue and dead-letter queue if imports are enabled, add encrypted Worker/CI secrets, deploy staging, verify health and migrations, then exercise two-account isolation and failure recovery. Production promotion requires real-provider coverage, quota checks, cron and queue monitoring, Apple webhook configuration, APNs delivery, account deletion/revocation, and retention cleanup. Keep rollback artifacts and explain whether rollback also requires a database restore. Never print secret values in commands or logs.

For App Store delivery, use fresh explicit app and extension identifiers, App Group, Keychain group, Sign in with Apple, push, and IAP capabilities only when selected. Archive with the current required Xcode/iOS SDK, upload to App Store Connect, test the processed build through TestFlight on a physical iPhone, and complete privacy, age-rating, export-compliance, content-rights, support, and review-access fields. Official references: https://developer.apple.com/programs/enroll/, https://developer.apple.com/documentation/xcode/distributing-your-app-for-beta-testing-and-releases, https://developer.apple.com/help/app-store-connect/test-a-beta-version/testflight-overview/, and https://developer.apple.com/app-store/review/guidelines/.

Finish by running every available local check and report the repository tree, architecture and data-flow diagrams, exact commands to run the demo and tests, enabled optional modules, required external accounts, credential variable names without values, manual console work, migration and rollback steps, monitoring and maintenance procedures, and all unverified live checks. State plainly that local fixtures and successful builds do not prove provider coverage, push delivery, store purchases, cross-device sync, provisioning, or App Review readiness.`;
