import "server-only";

export const robloxGamePrompt = `Build a production-quality Roblox game matching the brief as a clean-room project. Room decoration and social progression are the worked example below. Invent an original title, setting, item catalog, economy, artwork, UI language, audio, rewards, and balancing. Do not copy private source, names, identifiers, product IDs, place IDs, DataStore names, assets, exact prices, exact odds, layouts, or distinctive content from another game.

PRODUCT ADAPTATION: The customer brief and reviewed app specification take precedence over product examples in this foundation. Preserve an explicitly supplied original name, platform and requirements. Room decoration, placement, inventories, progression and social rewards below form an optional worked example. Derive the actual genre and core loop from the brief. For other genres replace those systems, data models and tests while retaining server authority, reliable persistence, safe multiplayer boundaries and platform purchase verification where applicable.

Use strict Luau with a Rojo project. Pin Rojo, Lune, and StyLua in rokit.toml. Map shared modules into ReplicatedStorage, authoritative services into ServerScriptService, and client controllers into StarterPlayerScripts. Keep game rules in pure shared modules that can run under Lune without Roblox services. Keep server orchestration thin and dependency-inject persistence, clocks, random sources, marketplace services, policy services, and messaging adapters. Client code may request actions and render state but must never decide currency, inventory, rewards, purchases, competition scores, or valid placement.

Create shared modules for the item catalog, profile domain, progression, room rules, placement bounds and sockets, activities, goals, customization, presentation competition, monetization definitions, audio configuration, and visual constants. Create server services for profiles, rooms, earnings, activities, visits, lobbies, competitions, rewards, monetization, and world construction. Create client controllers for the HUD, inventory, build editor, interactions, visits, activities, reveal sequences, purchases, competition, presentation cameras, audio, and responsive UI. Use one clearly named RemoteFunction for request-response mutations and RemoteEvents for snapshots or focused live updates. Define and validate a tagged action protocol rather than exposing one remote per unchecked action.

The core loop should be generic and tunable: a player receives a starter space, completes a short guided setup, earns soft currency through active presence or simple play, acquires randomized or guaranteed decor, places items, completes decorating goals, expands the room, visits others, and joins an optional room-presentation activity. Build all values from configuration tables. Include a small original sample catalog and make it obvious how the owner replaces it. Avoid dark patterns, fake scarcity, automatic purchase prompts, and rewards that require unverifiable social actions.

Define a versioned profile with revision, soft currencies, inventory keyed by unique item IDs, placements, discoveries, operation IDs, tutorial state, XP and level, room unlocks, upgrades, claimed goals, preferences, optional activity progress, optional unopened reward packs, optional presentation stats, and commerce receipt state. A placement records room, surface type, local transform, rotation, optional support parent, and optional authored socket. Validate finite values, ownership, parent acyclicity, catalog references, room access, bounds, collision, support capacity, wall and floor rules, and rotation increments.

Implement DataStore persistence using UpdateAsync through an adapter. Roblox documentation is at https://create.roblox.com/docs/cloud-services/data-stores. Use per-player session leases with owner and expiry, optimistic revision checks, schema migrations, exact snapshot retries, bounded operation deduplication, autosave, PlayerRemoving save, and BindToClose draining. Fail closed: if a profile cannot load or its lease is held elsewhere, do not grant a fresh writable profile. If saving fails, pause further economic mutations and present a retry or safe rejoin path. Preserve pending deterministic rewards so a failed acknowledgement cannot reroll a randomized item.

Studio must default to session-only persistence. Add an explicit configuration flag that enables Studio DataStores only for a separate private development experience whose API access was intentionally enabled. Never point automated or exploratory tests at the production DataStore. Document that changing the DataStore name after launch starts a new save namespace unless a migration is implemented.

Build a server-authoritative placement system supporting select, preview, rotate, place, move, store, and cancel. Provide an accessible walking mode and an optional overhead grid editor with pan, zoom, multiple camera angles, mouse, touch, keyboard, and gamepad input. The client computes responsive previews, but the server recomputes legal transforms and collision using catalog bounds. Support floor, wall, and surface-mounted items, parent-relative attachments, room ownership, unlocked-room checks, and decoration capacity. Reject NaN, infinity, stale item IDs, impossible distance, cross-room edits, collision, and forged parent relationships. Rate-limit actions and require an operation ID for every mutation.

Build progression as pure deterministic functions. Include configurable income, item rarity, room XP, level gates, goals, guaranteed purchases, duplicate recycling or combining, room extensions, and prestige as independent feature flags. Random reward selection must happen on the server using documented weights. Freeze the selected result before saving; reveal animations only display the committed result. Disclose odds wherever random rewards are offered. Protect special items, placed items, and a player's last required copy from accidental recycling. Add wallet and inventory caps with explicit overflow handling rather than silent loss.

Create optional short activities in isolated areas of the same place. The server owns the activity session, validates proximity and dwell time, and grants a predetermined completion result once. Practice grants nothing. Pause, leave, respawn, disconnect, and duplicate completion must be safe. Activity rewards may include currency, XP, a themed item, or a temporary earnings charge counter. Store only durable completion state; ephemeral steps can reset safely.

Add current-server visiting. Players choose private or server-visible access for the current session. A visitor can browse and inspect but cannot edit, earn from, spend for, or trigger rewards in another player's room. Closing access, owner departure, or an unsafe save state returns visitors home. Keep discovery current-server and text-based unless real thumbnail infrastructure is deliberately added. Do not claim cross-server visits: this template does not use TeleportService, MessagingService, or MemoryStoreService.

Add an optional current-server room-presentation competition. Implement lobby discovery, join and leave, countdown, locked participant lineup, deterministic phase state machine, private ratings, tie rules, disconnect handling, results, and idempotent rewards. Support solo practice with clearly labelled NPC decorators and no ranked or paid rewards. Keep camera cues and presentation choices client-side while scoring and phase transitions remain server-owned. Add current-server leaderboards derived from committed profiles; do not imply global ranking without OrderedDataStore design and budget analysis.

Roblox platform services are the only required external runtime. Use MarketplaceService only when monetization is enabled. The owner must create new developer products and passes in Creator Dashboard at https://create.roblox.com/dashboard/creations and insert placeholders through configuration. Official product guidance is https://create.roblox.com/docs/production/monetization/developer-products and pass guidance is https://create.roblox.com/docs/production/monetization/passes. Never reuse a product ID for a different reward after release because delayed receipts retain the original meaning.

Grant developer products only from MarketplaceService.ProcessReceipt after the entitlement and purchase ID have been durably saved together. Prompt completion events never grant products. Receipt replay, delayed receipt delivery, a full inventory, overflow, cancellation, server shutdown, and rejoin must not duplicate or lose value. Query localized price metadata for display instead of hardcoding Robux prices. Verify pass ownership on join, after purchase, and through an explicit restore action; store verified entitlement without stacking it repeatedly.

If paid random rewards exist, use PolicyService.GetPolicyInfoForPlayerAsync, fail closed when policy lookup fails, disclose exact odds before purchase, and preserve paid-currency provenance through spending and rewards. Follow https://create.roblox.com/docs/production/monetization/paid-random-items. Make monetization optional so the free progression loop remains fully playable. Require the owner to complete current content maturity and compliance questionnaires accurately and to test restricted-account behavior.

Use contextual ProximityPrompts for nearby world interactions, with server-side distance and ownership checks. Keep menus responsive at phone portrait, phone landscape, tablet, desktop, and television-safe dimensions. Support mouse, keyboard, touch, and gamepad; restore camera and movement state after editor, activity, visit, competition, respawn, or error. Provide independent music and effects levels, mute, reduced-effects mode, readable minimum text sizes, clear focus order, and alternatives to color-only rarity communication.

Art must be original and replaceable. Permit primitive fallback models and locally authored meshes, textures, thumbnails, and audio. Maintain a manifest with stable catalog IDs independent from asset IDs. Preload only the next-needed assets, apply level-of-detail policies, pool or cache repeated visuals, and degrade gracefully when editable-image or asset APIs are unavailable. Never embed another game's exported models or listing artwork.

Set up development with Roblox Studio from https://create.roblox.com/docs/studio/setup and Rojo from https://rojo.space/docs/v7/. The documented flow is: install pinned tools, run StyLua, run offline Lune suites, build both rbxl and rbxlx artifacts, open the generated place in Studio, and Play. For live sync, run Rojo on localhost, connect the matching Studio plugin, and restart the play session after script changes. Explain that Rojo synchronization does not save or publish the place and that source is authoritative; never save an older open place over a newly built artifact.

Write extensive offline tests against the real domain modules and service doubles. Cover profile validation and migrations, leases and competing sessions, revision conflicts, operation deduplication, interrupted exact-save recovery, random reward freezing, currency provenance, receipt replay, inventory and wallet overflow, placement bounds and rotated collision, support relationships, forged remotes, action rate limits, tutorial progression, goals, activities, visits, lobby phases, votes, ties, disconnects, NPC practice, responsive UI construction, and cleanup of camera and controls. Compile every source module in the test harness. Add deterministic multi-minute simulations that use only legal commands and earned resources.

Offline tests do not prove rendering, Roblox physics, live DataStore behavior, checkout, network ownership security, device ergonomics, or fun. Require Studio acceptance with fresh and migrated profiles, two or more clients, interrupted saves, rejoin, shutdown, every placement surface, small screens, touch, gamepad, low graphics quality, and poor network conditions. Before public launch, perform write-budget and load tests and batch or debounce frequent edits and payouts; committing every small mutation will not scale.

Build and release manually through Studio using https://create.roblox.com/docs/production/publishing/publish-experiences-and-places. The runbook must verify the target experience and start place, create a pre-release backup, build from clean source, run all offline checks, open the artifact, run Studio smoke tests, publish to a private test audience, verify new-server persistence and multiplayer behavior, then expand access. Keep product and pass configuration tied to the correct universe. Rollback must account for save-schema compatibility; never run older code against migrated data unless the migration is backward compatible or the matching data backup can be restored.

Finish with a README covering architecture, source map, controls, feature flags, catalog authoring, economy tuning, save schema, DataStore safety, remotes and trust boundaries, accessibility, testing, Studio workflow, publishing, monetization, compliance, performance budgets, incident response, and known limitations. Add checklists for first-session playtesting, placement, rejoin, multiplayer visits, competition, real-device UI, and purchases. Clearly label all placeholder IDs and all live actions the owner must perform in Studio or Creator Dashboard.`;
