import "server-only";

export const storefrontPrompt = String.raw`Build a production-ready, original ecommerce website for a small local business. Use the customization brief supplied with this prompt for the brand, catalog, currency, service area, fulfillment rules, voice, colors, and imagery. Treat all example content as synthetic placeholders. Do not reuse names, copy, artwork, prices, addresses, account identifiers, domain names, or source data from any reference project.

Deliver a complete repository that a developer can run locally and deploy to Cloudflare Pages. Use semantic HTML, modern CSS, and small framework-free browser JavaScript unless the customization brief explicitly calls for another stack. Put server-only work in Cloudflare Pages Functions. Keep the site fast, accessible, responsive, and usable without animation. The result must include source code, tests, setup documentation, an environment-variable example containing placeholder names only, privacy and terms placeholders, and an operations runbook.

Create a polished storefront with a skip link, responsive header and navigation, hero, trust points, catalog, fulfillment or delivery section, how-it-works section, FAQ, contact and social placeholders, footer, and a slide-over cart. Products must support stable internal SKU keys, names, descriptions, displayed prices, quantities, and optional customer customization text. Include empty, loading, success, cancellation, and recoverable error states. Persist the cart in localStorage as a convenience, but treat it as untrusted input. Support keyboard navigation, visible focus, correct labels and live regions, escape-to-close, focus return after dialogs, sufficient contrast, reduced motion, and useful layouts from small phones through wide screens.

Keep the product catalog in one obvious configuration module shared by UI generation and server validation where the runtime permits it. If static and function bundles cannot safely share one file, generate both views from a checked source-of-truth file during the build. Each product record should contain an internal SKU, active status, display metadata, currency, server-authoritative unit amount, Stripe Price environment-variable name, quantity bounds, and customization constraints. Never place a secret key or a private Price ID in browser code. Never accept an arbitrary Stripe Price ID, amount, currency, fulfillment fee, discount, or success URL from the browser.

Implement cart operations for add, remove, increment, decrement, clear, subtotal display, quantity caps, customization, and a configurable minimum order. Give users immediate feedback while also enforcing every business rule again on the server. Normalize whitespace in free text, enforce conservative length limits, reject unknown fields and SKUs, and safely render all customer input as text. Make fulfillment zones configurable and validate them server-side using a robust identifier such as an allowed postal-code set or a dedicated address-validation step. A cosmetic city selector alone must never establish eligibility. Explain where an operator updates products, availability, hours, order limits, pricing, delivery fees, tax behavior, and service zones.

Implement POST /api/create-checkout-session as a Cloudflare Pages Function. Parse JSON defensively, require at least one item, validate every SKU and integer quantity, calculate totals from the server catalog, enforce active products, minimum order, customization rules, and fulfillment eligibility, then create a Stripe-hosted Checkout Session in payment mode. Prefer the current supported Stripe SDK when it is compatible with the Pages runtime; otherwise use Stripe's HTTPS API with form encoding and a pinned API version. Use an idempotency key tied to a server-generated checkout attempt so retries cannot create duplicate sessions. Enable only operator-approved options such as promotion codes, phone collection, billing or shipping address collection, and automatic tax. Derive success and cancellation URLs from an allowlisted application origin. Return only the Checkout Session identifier and hosted URL needed by the browser.

Use Stripe-hosted Checkout so card data never passes through this application. Configure payment methods in the Stripe Dashboard and do not hardcode payment_method_types unless the business has a documented reason. Treat the success redirect as presentation only; it is never proof of payment. Display a neutral confirmation state while the order record is finalized from a verified webhook.

Implement POST /api/stripe-webhook. Read the raw request bytes before any JSON parser, verify the Stripe-Signature header with the endpoint signing secret and the official library where supported, and reject missing, invalid, or stale signatures. Persist each provider event ID under a uniqueness constraint before applying effects. Handle at least checkout.session.completed and checkout.session.async_payment_succeeded, plus asynchronous failure or expiration events when those payment methods are enabled. Retrieve or reconcile the authoritative Checkout Session when necessary. Make fulfillment creation exactly-once and idempotent even when webhooks repeat, arrive late, or arrive out of order. Acknowledge promptly and move slow notifications or fulfillment work to a durable queue if available.

Add durable order storage rather than relying on console logs. Use a managed database supported by the selected Cloudflare deployment, with migrations checked into the repository. Model ProductSnapshot, CheckoutAttempt, Order, OrderLine, FulfillmentContact, FulfillmentZone, Customization, and ProviderEvent. Store the price, name, tax and product snapshot used at purchase so later catalog edits do not rewrite history. Use explicit order states such as checkout_pending, paid, fulfillment_pending, fulfilled, cancelled, payment_failed, and refunded. Minimize personal data, define retention, restrict administrative access, and never log full addresses, phone numbers, emails, payment identifiers, raw webhook bodies, tokens, or secrets. If the customization brief chooses no database, clearly mark the site as a checkout prototype that is unsafe for real fulfillment and disable live-mode launch.

External services must be documented by status. Required for the complete implementation: Cloudflare Pages and Pages Functions for hosting and server routes; Stripe Checkout and Webhooks for payment; and the chosen durable database for orders and webhook deduplication. Optional: a Cloudflare custom domain and DNS, a transactional email provider for receipts or operator alerts, a queue for fulfillment jobs, analytics with consent controls, an address-validation provider, object storage for operator-owned product images, and a social account. Alternative payment or delivery platforms may be described as replacements, not silently combined with Stripe. Square or a third-party delivery marketplace is an architectural alternative and is not implemented unless selected in the customization brief. Do not claim inventory management, tax registration, accounting, refunds automation, email delivery, or courier dispatch unless each is actually implemented and tested.

Provide an .env.example with names and obvious placeholders only. At minimum document STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, one server-side Stripe Price ID variable per configured SKU, APP_URL, and database bindings or credentials. Add STRIPE_API_VERSION if the integration pins it in configuration and STRIPE_AUTOMATIC_TAX_ENABLED as an explicit false-by-default gate. Store production values in Cloudflare encrypted secrets. Use separate test and live Stripe credentials, least-privilege restricted keys where feasible, and rotation instructions. Never expose secrets through public variables, source maps, browser bundles, logs, screenshots, shell history, fixtures, or error responses.

Write a setup guide with exact operator steps and link to authoritative documentation:
- Cloudflare Pages Functions: https://developers.cloudflare.com/pages/functions/
- Cloudflare Pages environment variables and secrets: https://developers.cloudflare.com/pages/configuration/build-configuration/
- Stripe Checkout quickstart: https://docs.stripe.com/checkout/quickstart
- Stripe webhook signatures and local forwarding: https://docs.stripe.com/webhooks
- Stripe test cards and test clocks where applicable: https://docs.stripe.com/testing
- Stripe restricted keys and key handling: https://docs.stripe.com/keys/restricted-api-keys and https://docs.stripe.com/keys-best-practices
- Stripe Tax prerequisites: https://docs.stripe.com/tax/set-up

The setup guide must tell the operator to create products and one-time Prices in Stripe test mode, copy their IDs into matching server secrets, create a webhook endpoint for the deployed /api/stripe-webhook route, use the Stripe CLI to forward test webhooks locally, test success, cancellation, asynchronous completion, duplicate delivery, invalid signatures, unavailable products, invalid quantities, minimum-order failures, and fulfillment-zone rejection, then repeat a controlled smoke test with live credentials only after the business has approved catalog, refunds, privacy, fulfillment, and tax obligations. Enabling automatic_tax is not a substitute for registrations, product tax codes, customer address rules, or professional tax review.

Add a restrictive Content Security Policy appropriate to hosted Checkout and the exact image/font hosts selected. Add security headers, no-store responses for checkout endpoints, same-origin checks for mutations, input size limits, structured redacted errors, and rate limiting. Do not trust client totals or success query parameters. Add idempotency both when creating checkout sessions and when fulfilling paid orders. Provide a recovery path for a successful payment whose notification initially failed. Include a daily reconciliation job that compares unresolved local checkout attempts with Stripe and reports mismatches without including private customer data.

Test the pure catalog and order validator with meaningful unit tests. Test signature rejection and webhook deduplication, idempotent fulfillment, catalog mismatch, currency consistency, quantity bounds, text normalization, and service-zone rules. Add browser tests for cart persistence, keyboard behavior, focus handling, mobile drawer layout, minimum-order messaging, checkout loading/errors, success/cancel states, and reduced motion. Mock Stripe in automated tests; use Stripe test mode only for an explicit integration smoke test. Run HTML/accessibility checks and test at narrow phone, tablet, laptop, and desktop sizes.

Provide scripts for local static and Functions development, unit tests, browser tests, linting, and a production build. Document deployment through a Git-connected Cloudflare Pages project, required build settings, secret injection, migrations, webhook URL setup, and custom-domain attachment. Before every release, run tests and build, back up the order database where supported, apply backward-compatible migrations before dependent code, deploy, confirm the health endpoint, complete one test-mode checkout against the deployed preview, verify webhook-created order state, and inspect redacted logs. Roll back code without deleting order data; roll forward for schema incompatibilities.

Finish with an operator runbook covering catalog and Price changes, sold-out handling, webhook health and lag, failed-payment review, fulfillment retries, refunds, reconciliation, database backups, dependency updates, secret rotation, access review, privacy deletion requests, monitoring, and incident response. Price changes require new Stripe Prices and a controlled catalog revision; never mutate historical order snapshots. Include a service inventory table with required, optional, alternative, and unimplemented entries, the setup owner, credential or binding names, billing or quota risk, local mock strategy, health check, and safe removal or rotation procedure.

The finished project must be genuinely deployable, while remaining an original generic template. Clearly distinguish finished functionality from operator configuration and future extensions.`;
