// Deliberately curated: generated text can select resources, never supply executable URLs.
export const guideResources = {
  supabase: { name: "Supabase setup", url: "https://supabase.com/docs/guides/getting-started" },
  supabaseAuth: { name: "Supabase authentication", url: "https://supabase.com/docs/guides/auth" },
  supabaseRls: { name: "Supabase row-level security", url: "https://supabase.com/docs/guides/database/postgres/row-level-security" },
  supabaseStorage: { name: "Supabase file storage", url: "https://supabase.com/docs/guides/storage" },
  supabaseFunctions: { name: "Supabase server functions", url: "https://supabase.com/docs/guides/functions" },
  supabaseLocal: { name: "Supabase local development and migrations", url: "https://supabase.com/docs/guides/local-development" },
  supabaseProduction: { name: "Supabase production checklist", url: "https://supabase.com/docs/guides/deployment/going-into-prod" },
  supabasePricing: { name: "Supabase pricing", url: "https://supabase.com/pricing" },
  apple: { name: "Apple developer resources", url: "https://developer.apple.com/develop/" },
  appStore: { name: "App Store Connect help", url: "https://developer.apple.com/help/app-store-connect/" },
  storekit: { name: "Apple StoreKit", url: "https://developer.apple.com/documentation/storekit" },
  android: { name: "Android developer setup", url: "https://developer.android.com/get-started/overview" },
  playStore: { name: "Google Play Console help", url: "https://support.google.com/googleplay/android-developer/" },
  firebase: { name: "Firebase Cloud Messaging", url: "https://firebase.google.com/docs/cloud-messaging" },
  expo: { name: "Expo documentation", url: "https://docs.expo.dev/" },
  github: { name: "GitHub getting started", url: "https://docs.github.com/en/get-started" },
  node: { name: "Node.js download", url: "https://nodejs.org/en/download" },
  nextjs: { name: "Next.js setup", url: "https://nextjs.org/docs/app/getting-started/installation" },
  cloudflare: { name: "Cloudflare Workers documentation", url: "https://developers.cloudflare.com/workers/" },
  vercel: { name: "Vercel deployment documentation", url: "https://vercel.com/docs" },
  stripe: { name: "Stripe payments documentation", url: "https://docs.stripe.com/payments" },
  stripeWebhooks: { name: "Stripe webhook setup", url: "https://docs.stripe.com/webhooks" },
  resend: { name: "Resend email documentation", url: "https://resend.com/docs/introduction" },
  discord: { name: "Discord developer quick start", url: "https://docs.discord.com/developers/quick-start/getting-started" },
  roblox: { name: "Roblox Creator Hub", url: "https://create.roblox.com/docs" },
  unity: { name: "Unity documentation", url: "https://docs.unity.com/" },
  godot: { name: "Godot getting started", url: "https://docs.godotengine.org/en/stable/getting_started/introduction/" },
  phaser: { name: "Phaser documentation", url: "https://docs.phaser.io/" },
  accessibility: { name: "Web accessibility tutorials", url: "https://www.w3.org/WAI/tutorials/" },
  security: { name: "OWASP application security verification", url: "https://owasp.org/www-project-application-security-verification-standard/" },
} as const;
export type GuideResourceId = keyof typeof guideResources;
